### ISSUE TITLE
Question: Send message to ArtemisMQ

### ISSUE THREAD

**Issue by Bandiii** [amqp/rhea#105]
Hello,

I am pretty new in queues. I would like to create a simple test in nodejs. 
I would like to send a message e.g.: {"p1":"bbb", "p2""ccc"} to anycast "queue.input" address "queue.input" queue.
Is it possible it with rhea? I didn't find example for that, or just I missed it.
Thank you for help in advance.

**Comment by grs** [comment]
Yes, it is possible. The simple_send.js example can be used against artemis and you can then modify that as desired (to change the queue name, the content and number of messages etc).
