### ISSUE TITLE
Add capability to remove session and links while closing

### ISSUE THREAD

**Issue by amarzavery** [amqp/rhea#106]
Reference issue #104 

session.close() and link.close() close the local and remote peers today. It would be nice if some kind of optional flag can be provided to remove them from the internal map as well. This provides backwards compatibility. The method should internally find out whether the connection is closed. If yes, then it should also remove the link/session. Thus making it simple for the consumer.

I am not sure if this is true or not. Does closing the session also closes all the links on it? If yes, then this would be very useful. Session would act like a bucket. closing/removing it will automatically take care of everything.

**Comment by grs** [comment]
See https://github.com/amqp/rhea/pull/113 which I think will do what you want. The session/link will always be removed once it is fully closed by both peers or if it is closed locally at the point of disconnection.

**Comment by amarzavery** [comment]
fixed by #113
