### ISSUE TITLE
Question: Arbitrary Headers AMQ_SCHEDULED_DELAY

### ISSUE THREAD

**Issue by sp3c1** [amqp/rhea#107]
Wondering if you could set arbitrary headers like [AMQ_SCHEDULED_DELAY](https://b-439237b2-9900-4ac0-aebe-ed248e87df43-1.mq.eu-west-1.amazonaws.com:8162/admin/send.jsp?JMSDestination=examples&JMSDestinationType=queue).

Would it just be?
```
.send({body: {}, headers: {amq_scheduled_delay: 1}}
```

Would be good to add to doc anyway how to handle headers.

**Comment by grs** [comment]
```
.send({body: {}, application_properties: {AMQ_SCHEDULED_DELAY: 1}}
```
(See https://github.com/amqp/rhea#sendmsg for a brief description of message format)

**Comment by sp3c1** [comment]
Thanks!
