### ISSUE TITLE
Asynchronous SASL mechanisms

### ISSUE THREAD

**Issue by pierreca** [amqp/rhea#110]
Some backstory here: https://github.com/amqp/rhea/issues/41
cc @anthonyvercolano

we're nearing the end of our migration work from amqp10 to rhea and the last piece of the puzzle is the SASL mechanism we use with our device provisioning service that relies on TPM operations that are asynchronous: basically, whenever we get a challenge frame, we need to have the TPM do something and asynchronously give us a signed response, and then we send that response - so the current synchronous API wouldn't work for us.

@grs, earlier in #41 you said that you may be interested in looking at how to make this API asynchronous - is it still the case? would you rather take that on or receive a pull request?

**Comment by grs** [comment]
@pierreca I'm happy either way. A PR might be faster.

**Comment by pierreca** [comment]
@grs - I'm looking at it now. I'm curious as to what your preference would be with regards to modifying existing code:
1. make everything asynchronous? Wouldn't that be a breaking change for folks who implement their own SASL mechanism, if anyone?
2. change the SaslClient code to "detect" if a sasl mechanism is async or synchronous and call next or nextAsync() for example? that'd duplicate some code paths just to deal with async vs sync mechanisms but would likely be more easily non-breaking.

what would you rather do with the existing mechanisms?

**Comment by grs** [comment]
I haven't really thought about it in detail. I would not object to a breaking change for custom sasl mechanisms though. I'm not aware of anyone using that api as yet, we can bump the version and I imagine it would not be too difficult to modify any existing extension.
