### ISSUE TITLE
amqp:data:binary vs amqp:amqp-value:*

### ISSUE THREAD

**Issue by anthonyvercolano** [amqp/rhea#115]
I have some json that I'm sending to a peer.  The stringified json looks like:

{"foo":1,"bar":{"baz":2,"tweedle":{"dee":3}}}

The beginning of the hex for this looks like:
7b22666f6f223a312c22626172223a.....

In amqp10 the beginning of the composition looks like:
005375a02d7b22666f6f223a312c22626172223a...

So amqp10 looks like it is using amqp:data:binary

In rhea the beginning of the composition looks like:
005377a02d7b22666f6f223a312c22626172223a...

So rhea looks like it is using amqp:amqp-value:*

I can get this far with rhea by doing
amqpMessage.body = new Buffer(body);

And later sending this to link.send.

Any thoughts on what I should do to get it to use the amqp:data:binary?

**Comment by amarzavery** [comment]
rhea.types.wrap_binary(foo)

**Comment by anthonyvercolano** [comment]
Doing this really blows up the xfer frame.  Seems to add almost a couple of hundred bytes.

This is all a bit strange.

This is what I use to send telemetry data to my peer:
amqpMessage.body = rhea.message.data_section(new Buffer(body));

This apparently works just great.

This is what I had used to send my twin updates which is using a separate sender link from the telemetry sender. I tested this twin code a month or so ago.  It worked.
Then I've made a few other changes in my code and also caught up on the latest changes in our master branch.
This code broke.  Everything else is fine.

So, I've put out the frame that our amqp10 implementation generates.
If I use the simplied amqpMessage.body = body; or the amqpMessage.body = new Buffer(body) I get pretty close to what amqp10 generates.  However,  the peer still doesn't seem to like it.  The biggest difference seems to be the 77 vs the 75.

**Comment by grs** [comment]
rhea.message.data_section is the right thing to use to get a data section (wrapping as binary alone will merely send the value as a binary value in an AMQP Value section)

What is the problem/error you have with using the data_section()?

**Comment by anthonyvercolano** [comment]
If you change line 139 of message.js to
```
    if (msg.body && msg.body.constructor.name === 'Section') {
```
My code now works.

The problem is that we are including rhea in two difference packages of our stack.  Which breaks the current type comparison.

**Comment by anthonyvercolano** [comment]
That is: given the change to line 139 above, the code
```
amqpMessage.body = rhea.message.data_section(new Buffer(body));
```
Now works.

Why this probably worked a month or so ago is that I was symlink'ing to one local copy of rhea where I was using some adjusted logging.

**Comment by anthonyvercolano** [comment]
Would you take the change as a PR?

**Comment by grs** [comment]
@anthonyvercolano Would this work for you: https://github.com/amqp/rhea/pull/116?

**Comment by anthonyvercolano** [comment]
It appears to work.  Ship it.

**Comment by amarzavery** [comment]
@grs After the PR is merged can you publish   a new version of rhea
