### ISSUE TITLE
Way to distinguish between link's is_closed() and it's underlying session's is_closed()

### ISSUE THREAD

**Issue by amarzavery** [amqp/rhea#117]
Today link's is_closed() method looks like this:

```js
link.is_closed = function () {
    return this.session.is_closed() || this.state.is_closed();
};
```

where it returns true if the session was closed by the client or the link itself was closed by the client (by returning the value of `this.state.is_closed()`).

To keep things simple, when I receive a detach for the sender link
```
2018-08-07T16:59:16.202Z rhea:frames [connection-1]:1 <- detach#16 {"closed":true} 
2018-08-07T16:59:16.203Z rhea:events [connection-1] Link got event: sender_close
```
I close it's underlying session as well, rather than reusing it. Thus I do not have to worry about the scenario where I am in the process of establishing the sender link and the reused session dies.

However because of the current implementation of `link.is_closed()`, it returns `true` when its underlying session is closed as well. It would be nice if there could be method that can tell explicitly whether only the link was closed by the client.

Is this possible?

**Comment by grs** [comment]
I think a separate method is nicer. Perhaps is_link_itself_closed() or is that too long-winded?

**Comment by amarzavery** [comment]
- link.is_itself_closed()
- session.is_itself_closed()
and some documentation in the type definitions that explains the difference between this and the other variant *.is_closed()

**Comment by grs** [comment]
Ok, sounds good, do you want to create a PR?

**Comment by amarzavery** [comment]
Sure. Will be there in few minutes.
