### ISSUE TITLE
"legacy-amqp-topic-binding" filter

### ISSUE THREAD

**Issue by jawilson** [amqp/rhea#125]
Is it possible to use the `legacy-amqp-topic-binding` filter with ActiveMQ?

**Comment by grs** [comment]
No, I don't believe so. You should be able to use a selector filter though (https://github.com/amqp/rhea/blob/master/examples/selector/recv.js#L44)

**Comment by jawilson** [comment]
Thanks for the quick reply! I did manage to get that working, but I was hoping to avoid selectors because I'll be deploying with AmazonMQ and they [recommend against using message selectors](https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/connecting-to-amazon-mq.html#avoid-using-message-selectors).

**Comment by grs** [comment]
Just to clarify the issue is that the AmazonMQ broker does not support the legacy-amqp-topic-binding (it was targetted at pre 1.0 AMQP implementations).
