### ISSUE TITLE
Support (any examples?) for amqps with username and password?

### ISSUE THREAD

**Issue by git-ashish** [amqp/rhea#127]
Does this library support **amqps** with username and password? If so, would the connection param look any different than the normal one using a username, password, host and port?

Thanks!

**Comment by grs** [comment]
Yes, just specify transport as tls. You can also specify username, password as for plain tcp connection.

**Comment by git-ashish** [comment]
Thanks @grs! Currently, I'm seeing following error in the logs with 'tls' specified.

`ERR    [connection-1] disconnected Error: self signed certificate (connecting to custom-domain-name:51016)
`
51016 is the port where amqps is running.

Any clues?

We do have an issue with the https certificate on our custom domain. Do you think it is because of that and should go away if the certificate is fixed?

Is there any option to skip the certificate verfication in the library like mentioned [here](https://blog.effectivemessaging.com/2015/09/disabling-ssl-hostname-verficiation-in.html) for other amqps clients?

**Comment by grs** [comment]
Yes, you can add rejectUnauthorized: false to the connection options and that will proceed with the self signed certificate.

(Or else  sign a cert with a separate CA, and pass in the ca cert, see the tls examples).

**Comment by git-ashish** [comment]
Thanks so much! I'll test and let you know.

**Comment by git-ashish** [comment]
The connection is working with **rejectUnauthorized: false** setting. Thanks a lot for your super quick help @grs!
