### ISSUE TITLE
inspecting headers on received message

### ISSUE THREAD

**Issue by archerabi** [amqp/rhea#137]
I've noticed that in the receive listener, `context.message` doesn't have any headers. I only see `message.body` and `message.ttl`. Is it possible to get the headers, i need the `delivery_count`

**Comment by grs** [comment]
delivery_count will be on the message itself if it has been set (as for ttl, another header field)

**Comment by archerabi** [comment]
Okay, i see it now. I guess it has to be set by the broker to be available. Thank you.
