### ISSUE TITLE
Understanding credit_window

### ISSUE THREAD

**Issue by Gadi-Manor** [amqp/rhea#148]
Does credit_window=X means only X messages will be delivered from the broker and only when one is settled then the next one will be delivered? 
I'm trying to limit the number of messages my consumer can handle at once. I set credit_window=5 and credit window=0 and in both cases I didn't see any change. 
I guess I'm missing something.

**Comment by grs** [comment]
How are you setting it? If set to 0, you will need to manually issue credit for any messages you want (have a look at the drain example). A non-zero value will cause the library to issue credit to ensure that no more than that many messages are buffered waiting to be processed. The credit window is not tied to settlement.

**Comment by Gadi-Manor** [comment]
I just added to the options I sent to open_receiver() the parameter credit_window.
Small update, I had a little mistake and now when I set credit_window=0 I don't get any messages which I guess is what's supposed to happened. It was fixed once I set autoaccept=false.

Basically what I want to achieve is limit the number of messages I can handle at once, let's say to 5.
I was able to achieve it by setting credit_window=0 (in the options as mentioned above) followed by receiver.add_credit(5). 
Then, for every settled message I call add_credit(1). Is that the way to 'ask' for more messages? 

On the other hand, when I set credit-window=5 in the options sent to open_receiver() I still got all the messages (which is a lot more). Wasn't it supposed to be equivalent to steps described earlier?

**Comment by grs** [comment]
The idea of the window is that it moves as you handle the message events. If the window is 5, you will never have more than 5 messages buffered up before your application sees them in the 'message' event. However once the event has been processed for a given message, the window can move forward, allowing another message to be sent in place of the one just processed.

If you want to tie the window to completion of processing in some other way, e.g. settlement, then for now at least you should manage credit explicitly and basically re-issue credit either on settlement on every message or in batches if preferred.

**Comment by Gadi-Manor** [comment]
Now things start to make sense, Thanks a lot!
