### ISSUE TITLE
Message Encoding Issue Amazon MQ

### ISSUE THREAD

**Issue by bkowski** [amqp/rhea#153]
Hi
We have an Amazon MQ broker using ActiveMQ 5.15.6 and are seeing encoding issues with all messages sent using rhea, see attached screenshot showing the message received from the hello world example. We were after some advice as to what may be causing this.

![screen shot 2018-10-31 at 10 13 02 pm](https://user-images.githubusercontent.com/8274371/47784694-72588880-dd5a-11e8-8b78-ee2c49011b68.png)

**Comment by grs** [comment]
Do you have the transport.transformer set (http://activemq.apache.org/amqp.html)? Is that screenshot from the activemq console?

**Comment by bkowski** [comment]
> Do you have the transport.transformer set (http://activemq.apache.org/amqp.html)? Is that screenshot from the activemq console?

Hi thanks for the reply, by default the transformer is set to 'native', see attached screenshot showing all message details in activemq console. There are 2 other options available for the transformer 'jms' and 'raw', do you think the native transformer strategy could be causing this issue?

![screen shot 2018-11-01 at 9 45 37 am](https://user-images.githubusercontent.com/8274371/47823226-56d19a00-ddbb-11e8-8a1b-a41660d79f21.png)

**Comment by grs** [comment]
Yes, I think with 'native' the body of the message is the encoded bytes in AMQP (which includes header- and property- sections). If you set it to 'jms' it should set the body o fthe internal message to justthe decoded body of the AMQP message.

**Comment by bkowski** [comment]
Thanks for your help on this issue, we ended up going with a stomp client as there was no changes required to the broker. We are not sure to what degree we can customise the Amazon mq service.
