### ISSUE TITLE
Is it possible to reduce credit?

### ISSUE THREAD

**Issue by Gadi-Manor** [amqp/rhea#156]
I set credit_window=0 and then add_credit(n).
Now I want to reduce the credit so I'll get less then n messages or even stop all messages completely. 
Is is at as simple as adding credit or the only solution is to re-open the receiver with the desired credit?

**Comment by grs** [comment]
The safe way to do it is to drain the credit: https://github.com/amqp/rhea/blob/master/examples/drain.js#L37

**Comment by Gadi-Manor** [comment]
I looked at the example but I think I'm still missing something.
Can you please explain what does setting receiver.drain to true/false means?
Thanks in advance.

**Comment by grs** [comment]
if you set drain to true and then issue a flow, the library will request the server to use up all the outstanding credit it can, which leaves ut with zero credit whether or not it can send all the messages.

**Comment by Gadi-Manor** [comment]
Thanks. 
So to see I get things right,
If I set credit_window=0 followed by add_credit(n) the receiver could get up to n messages,
Then if I want the receiver to not get any messages what I should do is:
`recevier.drain = true;
receiver.add_credit(x) //x is any number`

And when I want the receiver to start receiving again I should:
`credit.drain = false;
credit.add(n)`

Is that right?

**Comment by grs** [comment]
The 'not get any messages' but isn't guaranteed; once you have issued the credit the sende rcan send you that many messages. But the drain offers a way of safely reducing the outstanding credit down to 0. So if there are messages in flight or just ready to be sent, you will get them but you won't leave credit waiting for messages that don't exist.

**Comment by Gadi-Manor** [comment]
Thanks, helped a lot!
There is just one problem now. Because I'm setting drain=true and then flow(n) then the receiver.credit is equal to n although it's supposed to be 0 (and in fact no messages are received). 
Is there anyway of knowing the actual credit?

**Comment by grs** [comment]
Once you get the drained event, the actual credit will be zero (and will only change from that if you add credit). However the credit property of the receiver should really reflect that. I've checked in a fix for that: https://github.com/amqp/rhea/commit/ce36498dd4433a416fe5c62800d921f56fd42cca

**Comment by Gadi-Manor** [comment]
Great, Thanks!
