### ISSUE TITLE
Is there a way of getting a list of all queues and topics?

### ISSUE THREAD

**Issue by Gadi-Manor** [amqp/rhea#160]

**Comment by grs** [comment]
That depends on the broker used. Most brokers offer a message based protocol for requests like this. If they do, and if AMQP 1.0 is supported for that, then you can use rhea.

**Comment by Gadi-Manor** [comment]
I'm using Apache ActiveMQ. I'm guessing it's possible because I found [this ](https://stackoverflow.com/questions/24212496/is-it-possible-to-get-a-list-of-queues-on-a-remote-broker) code in JAVA.

But I'm not exactly sure what should I do to achieve it in rhea.

**Comment by grs** [comment]
I believe it is not currently possible to use AMQP to get this information from activemq5. You could use http potentially https://gist.github.com/yashpatil/de7437522bfccfeee4cb

**Comment by Gadi-Manor** [comment]
Thanks.
I'll try attacking it from another angle, Can I use wildcard on receive? e.g. receive from all queues that starts with 'SomePrefix.*'

**Comment by grs** [comment]
I know you can use wildcards on topics. I don't think it would work across distinct queues. You could perhaps configure composite destinations (http://activemq.apache.org/composite-destinations.html). I'm not an activemq expert though, so perhaps ask on the activemq user list?

**Comment by Gadi-Manor** [comment]
Thanks.

> Most brokers offer a message based protocol for requests like this. If they do, and if AMQP 1.0 is supported for that, then you can use rhea.

I'm returning to this for a second because It's not entirely clear for me. 
I found a way to get these queues from command line when I run the broker locally. Can I use rhea to help me do the same?

**Comment by grs** [comment]
rhea just speaks amqp 1.0, so unless the broker allows amqp 1.0 based message queries for that sort of information (and some brokers do, e.g. activemq artemis, qpid brokers etc) then rhea can't help you. From what I have been able to ascertain it *may* be possible to get advisories over amqp, but there are probably lots of encoding issues with that so it would not be trivial. The 'native' protocol so to speak of active,q is openwire, which is probably what the command line tool you use uses (or else http)

**Comment by Gadi-Manor** [comment]
In case anyone else is having this issue I have found a way of retrieving all queues and topics names (among other statistic) while working with `Apache ActiveMQ`. 

As written in [here](http://activemq.apache.org/statisticsplugin.html) to get statistic for a queue what needs to be done is to send an empty message to `ActiveMQ.Statistics.Destination.<destination-name>` and set the `replyTo` in the header to another queue which will receive the result(s). 

Now, since wildcards are also supported, to get the statistics for all queues what we need to do is to send a message to `ActiveMQ.Statistics.Destination.>` with the following parameters: `{ body: '', reply_to: 'myQueue'}`

For every queue a message will be sent to `myQueue` with all that queue statistics. One of the fields is `destinationName` that holds that queue name.
