### ISSUE TITLE
DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

### ISSUE THREAD

**Issue by amarzavery** [amqp/rhea#162]
```
$ node -v
v10.13.0
```

rhea:frames [connection-1]:0 -> disposition#15 {"role":true,"settled":true,"state":[]}  +3ms
  rhea:raw [connection-1] SENT: 28 0000001c02000000005315d00000000c000000054143434100532445 +3ms
(node:6754) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

This would probably help. https://nodejs.org/docs/latest/api/util.html#util_util_inspect_custom. (Not sure if this would be supported in older versions of node.js)

Note: It is not a blocking issue. However, it would be nice if Object.inspect can be replaced.

**Comment by grs** [comment]
I've removed that method; I don't think it was used in normal paths. How did you trigger the above warning?

**Comment by amarzavery** [comment]
It appears in the logs. Have latest version of node 10 installed..
Also make sure to update the typings, if the method is being removed.
