### ISSUE TITLE
RPC server/client in container

### ISSUE THREAD

**Issue by GaikwadPratik** [amqp/rhea#169]
I see that `rpc_server` and `rpc_client` implemented in `Container` class. Is there any reason they are not included in typescript definitions? Also can we rename them as `createRpcServer` and `createRpcClient` respectively?

**Comment by grs** [comment]
I want to remove those or replace them with something better.

**Comment by GaikwadPratik** [comment]
@grs, Continuing discussion from https://github.com/amqp/rhea-promise/issues/24. 

As per your comment on the other issue, that you want to remove/replace `RpcServer/RpcClient` from rhea module. Our application is currently dependent on `RpcClient.call`. 

1. Can you suggest any alternative to that? 
2. Out of curiosity, what are issues associated with current `Rpc` module? Perhaps we can fix those or improve the `Rpc` module. I tested those and it works

**Comment by GaikwadPratik** [comment]
@grs Do you have any replacement in mind? Perhaps we can start with that... Right now it is the only hard stop for our application to migration to `Rhea`.

**Comment by grs** [comment]
My recommendation would be to implement a simple request-response layer in your own application.

**Comment by amarzavery** [comment]
@GaikwadPratik - I have done something similar over [here](https://github.com/Azure/amqp-common-js/blob/master/lib/requestResponseLink.ts). May be it can help you.

**Comment by grs** [comment]
@GaikwadPratik the api to the rpc functionality was not sufficiently well thought through. I think there are two aspects, a flexible request-response layer and then rpc proper on top of that. It is not really core the the purpose of rhea and as @amarzavery says it is easy to implement something for a specific case.

**Comment by GaikwadPratik** [comment]
I needed both server and client of RPC. So I have created [this](https://github.com/GaikwadPratik/rhea-rpc) 
as a replacemnet of [amqp10-rpc](https://github.com/mbroadst/amqp10-rpc).
