### ISSUE TITLE
receiver.is_closed() returns true when ECONNRESET error happens

### ISSUE THREAD

**Issue by amarzavery** [amqp/rhea#170]
We are using the *.is_closed() method to distinguish between the user of the sdk trying to close the sender/receiver v/s the link getting closed/disconnected due to external factors.

Some customers reported in [this issue](https://github.com/Azure/azure-event-hubs-node/issues/174) that when the ECONNRESET error happens, the sdk does not reconnect the receiver link.

Based on the provided logs it seems that we do not reconnect since receiver.is_closed() returns `true`, indicating the sdk that the user initiated the close, which is clearly not the case.

```bash
2018-11-28T20:41:56.791Z azure:event-hubs:error [connection-1] Error (context.error) occurred on the amqp connection: { Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
2018-11-28T20:41:56.791Z azure:event-hubs:error [connection-1] state: { wasConnectionCloseCalled: false,
  numSenders: 0,
  numReceivers: 58 }
2018-11-28T20:41:56.791Z azure:event-hubs:error [connection-1] connection.close() was not called from the sdk and there were some sender or receiver links or both. We should reconnect.
2018-11-28T20:41:57.092Z azure:event-hubs:error [connection-1] calling detached on receiver '656c5642-c480-4ae8-9e7d-6a4834b0a247' with address '***/ConsumerGroups/$default/Partitions/0'.
2018-11-28T20:41:57.094Z rhea-promise:error [connection-1] The receiver is open ? -> false


...


2018-11-28T20:41:57.143Z azure:event-hubs:error [connection-1] Something is busted. State of Receiver '656c5642-c480-4ae8-9e7d-6a4834b0a247' with address '***/ConsumerGroups/$default/Partitions/0' is: {
  wasCloseInitiated: true, <<<<<<<<<<<<<<<<<<<<<<<<<<<< This is true>>>>>>>>>>>>>>>
  receiverError: undefined,
  _receiver: 
   Receiver {
     domain: null,
     _events: 
      { message: [Function],
        receiver_error: [Function],
        receiver_close: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     actionInitiated: 0,
     type: 'receiver',
     _session: 
      Session {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        actionInitiated: 0,
        _connection: [Object],
        _session: [Object] },
     _link: 
      Receiver {
        session: [Object],
        connection: [Object],
        name: '656c5642-c480-4ae8-9e7d-6a4834b0a247',
        options: [Object],
        state: [Object],
        issue_flow: false,
        local: [Object],
        remote: [Object],
        delivery_count: 0,
        credit: 1000,
        observers: [Object],
        drain: false,
        _events: [Object],
        _eventsCount: 7 },
     linkOptions: 
      { name: '656c5642-c480-4ae8-9e7d-6a4834b0a247',
        autoaccept: true,
        source: [Object],
        credit_window: 1000,
        onMessage: [Function],
        onError: [Function],
        onClose: [Function],
        onSessionError: [Function],
        onSessionClose: [Function] } } }
```

```js
const wasCloseInitiated = this._receiver && this._receiver.isClosed(); // This returns true.
```

Question:
1. Could this be a bug in rhea that receiver.is_closed() returns `true` on `ECONNRESET`?

**Comment by ramya-rao-a** [comment]
@grs We found another case of ECONNRESET where even the `is_itself_closed()` on the receiver link returns `true`. 

To replicate, disable your network/wifi in the midst of receiving messages. This results in the ECONNRESET error and the `is_itself_closed()` on the receiver link returning `true`. 

With this information, is it right to assume that we cannot rely on `is_itself_closed()` on the receiver link to determine if the client application closed the link explicitly or not?

**Comment by grs** [comment]
Do you have an example with which you can reproduce/demonstrate the problem?

**Comment by ramya-rao-a** [comment]
@grs I dont have an example directly working with rhea yet, will an example that uses our [Event Hubs SDK](https://www.npmjs.com/package/@azure/event-hubs) that uses rhea be ok?

**Comment by grs** [comment]
On disconnection, all the endpoints are reset. On reconnection those that were open are then reopened. However between these, the is_itself_closed() will still return true. I have pushed a fix for that now such that in the disconnected state all endpoints that were open at the point of disconnect will return false for is_itself_closed().

**Comment by ramya-rao-a** [comment]
Thanks @grs!
Any ETA on when the next version of rhea will be released?

**Comment by grs** [comment]
@ramya-rao-a if you can verify this fixes things for you, I can get a release out immediately after that (e.g. tomorrow).

**Comment by ramya-rao-a** [comment]
@grs We can confirm that the fix works for us. `is_itself_closed()` returns `false` as expected.

**Comment by grs** [comment]
@ramya-rao-a 0.3.10 now published

**Comment by ramya-rao-a** [comment]
Thanks @grs!
I believe this issue can now be closed.
