### ISSUE TITLE
TypeError: "value" argument is out of bounds

### ISSUE THREAD

**Issue by kirstein** [amqp/rhea#173]
Hey!

I have been hitting buffer out of bounds for bigger payloads.

```
TypeError: "value" argument is out of bounds
    at checkInt (buffer.js:1185:11)
    at Buffer.writeUInt32BE (buffer.js:1278:5)
```

Failed written type:
```
TypeDesc {
  name: 'Uint',
  typecode: 112,
  width: 4,
  category: 1,
  read: [Function: read],
  write: [Function: write],
  create: { [Function] typecode: 112 } }

// value: 7469878655
```

Let me know what further information you require to clear up the issue

**Comment by grs** [comment]
7469878655 is indeed to large to be written as a uint. Do you have a reproducer that causes this error?

**Comment by kirstein** [comment]
Ok, figure it out. It was credit management. Accidentally I managed to add 7469878655 credits to a receiver.

**Comment by grs** [comment]
Ah! Thanks for figuring that out, We could certainly add some checking on that to give a more immediate and obvious error. I've raised an issue for that: https://github.com/amqp/rhea/issues/174

**Comment by kirstein** [comment]
Thanks! Closing this issue now!

**Comment by krisalay** [comment]
@kirstein 
Hello, 
I am facing the same issue.
Can you please let me know about the solution you used to resolve this issue?

**Comment by dbit-xia** [comment]
This error occurs when the filter has <>''
