### ISSUE TITLE
Settling a message after receiving doesnt remove it from the circular buffer

### ISSUE THREAD

**Issue by ramya-rao-a** [amqp/rhea#178]
@grs, @amarzavery,

From https://github.com/amqp/rhea/issues/166#issuecomment-441984137,
> To be removed, a delivery needs to be settled by peer as well as local application (i.e. both sides say they are finished with it).

The Service Bus SDK (local application) sends a request to settle the message by calling either [`delivery.accept()`](https://github.com/Azure/azure-service-bus-node/blob/99b6bff5566f3f8499c8f38a97c7e9f37471cc55/lib/core/messageReceiver.ts#L798), or [`delivery.modified()`](https://github.com/Azure/azure-service-bus-node/blob/99b6bff5566f3f8499c8f38a97c7e9f37471cc55/lib/core/messageReceiver.ts#L804)

The remote application (Service Bus) settles the message and `rhea` fires [the `settled` event](https://github.com/amqp/rhea/blob/master/lib/session.js#L401)

At this point, as far as I understand, both the local and remote applications have said that they are finished with the message.

But the circular buffer continues to keep the delivery and so we have the issue https://github.com/Azure/azure-service-bus-node/issues/89

Shouldnt we be running `delivery.update(true)` before firing the `settled` event as by this point it is clear that both sides have said that they are done with the message?

**Comment by grs** [comment]
If the receiver-settle-mode is 1 (i.e. receiver settles second), then the first accept() or modified() will not settle it locally. It will need to be settled once the sender has indicated that it has settled it e.g.:

  receiver.on('settled', function (context) { context.delivery.settled = true; });

We could certainly add an autosettle option to the receiver when the receiver-settle-mode is second to do this automatically by default.
