### ISSUE TITLE
Max retry count

### ISSUE THREAD

**Issue by arieljake-bluescape** [amqp/rhea#191]
Is there a property we can set either when opening the sender connection or in the message that will define the max number of times to retry a message before it is simply deleted by the queue?

**Comment by arieljake-bluescape** [comment]
I see this property in the activemq <-> amqp docs:

`header.deliveryCount`

Is this what I need?

**Comment by grs** [comment]
I believe you would have to configure that on the broker. (e.g. http://activemq.apache.org/redelivery-policy.html). I'm not aware of any property that can be set in a message itself to control this (I am not an expert on activemq configuration however).

**Comment by arieljake-bluescape** [comment]
That makes sense. Thank you.
