### ISSUE TITLE
Unable to establish connection with AmazonMQ

### ISSUE THREAD

**Issue by stephenbryantaustin** [amqp/rhea#198]
Hi Folks,

I'm trying to connect to Amazon MQ (ActiveMQ 5.15.8) from an EC2 instance within the VPC. Connecting using Python and Qpid Proton .27 is successful, but using the same credentials within a connect.json file fails. Here is the code:

```
var container = require('rhea');
// var container = rhea.create_container();

container.on('connection_open', function(context){
    console.log('Connected!');
});

container.connect();

```

Here's the error
`[connection-1] disconnected Error: getaddrinfo ENOTFOUND amqps://************.mq.us-east-1.amazonaws.com amqps://************.mq.us-east-1.amazonaws.com:5671`

connect.json:
`{
  "host": "amqps://*****.mq.us-east-1.amazonaws.com",
  "port": 5671,
  "user": "*****",
  "password": "*****"
}`

Based on the README it seems like this should work. Any help would be appreciated!

**Comment by grs** [comment]
don't put 'amqps://' in the hostname, instead set the scheme to be 'amqps'

**Comment by stephenbryantaustin** [comment]
Great thank you for the prompt response! I updated the connect.json to:
'{ "host": "*****.mq.us-east-1.amazonaws.com", "port": 5671, "user": "*****", "password": "*****", "scheme": "amqps" }'

Working great, should have asked sooner. Is this documented somewhere?

**Comment by grs** [comment]
The format is defined by proton, rhea copies that for convenience: https://issues.apache.org/jira/browse/PROTON-1935

**Comment by grs** [comment]
I should document it here as well of course
