### ISSUE TITLE
can't open a receiver bound to application header x-match expression

### ISSUE THREAD

**Issue by beaver71** [amqp/rhea#200]
I'm trying to adapt https://github.com/amqp/rhea/tree/master/examples/selector example using an x-match expression instead of a JMS expression.
Tried this code:

```
connection.open_receiver({
	source: {
		address: 'amq.match',
		filter: {
			'x-match': 'all',
			value: {
				'nat': 'it',
				'prod': 'a22'
			}
		}
	}
})
```

Received "connection_error Expected value type is 'Filter' but got 'String' amqp:decode-error" from Qpidd Java broker (rel. 7.1.0).

**Comment by grs** [comment]
The filter needs to be a described value. Try something like this:

```
connection.open_receiver({source:{address:'amq.match', filter:{'foo':amqp_types.wrap_described({'nat': 'it','prod': 'a22', 'x-match': 'all'}, 0x468C00000002)}}});
```

**Comment by beaver71** [comment]
Ok, thanks a lot for the quick response.
Now I don't receive any error from the broker, but no headers routing is applied...

I'm used to RabbitMQ (and AMQP 0.9.1) headers routing which is really straightforward, on the contrary I can't find any clear documentation or example on how to do something similar in AMQP 1.0.

**Comment by grs** [comment]
My first suggestion would be to use a JMS selector: https://github.com/amqp/rhea/blob/master/examples/selector/recv.js#L44. That would work with more brokers and is also richer than the headers exchange.

The example above was typed straight into the comment, I didn't try it out myself so its possible I git it slightly wrong. It should certainly be possible to get it working if you prefer the pre-1.0 headers exchange approach

**Comment by beaver71** [comment]
I tried JMS selector (your example or similar) and yes it works with several 1.0 brokers: ActiveMQ, Qpid cpp, Qpid java.
Anyway I'd like to make headers routing work with all the borkers above.

**Comment by beaver71** [comment]
Ok, thanks again.
I confirm, I tried the x-match filter using ActiveMQ, Qpid cpp, Qpid java, and it works only with Qpid cpp.

**Comment by k-wall** [comment]
@beaver71 Just to confirm, Apache Qpid Broker-J doesn't implement filter definition <descriptor name="apache.org:legacy-amqp-headers-binding:map" code="0x0000468C:0x00000002"/>, so it just rejects the messages and logs like so:

```2019-03-05 22:23:20,428 INFO  [IO-/127.0.0.1:57946] (q.m.e.discardmsg) - [con:0(guest@/127.0.0.1:57946/default)/ch:0] EXH-1003 : Discarded Message : Name: "amq.match" Routing Key: ""```

From a very quick glance, it probably wouldn't be too hard to add support (take a look at ExchangeSendingDestination.java), so if you want to raise a PR head over to https://github.com/apache/qpid-broker-j.

**Comment by beaver71** [comment]
@k-wall I tried JMS filters (example here on rhea repo) and it works fine with Qpid Broker-J but using "amq.topic" exchange instead of "amq.match" (so strange)

**Comment by beaver71** [comment]
I wrote a question also on Stackoverflow: https://stackoverflow.com/questions/54981423/cant-open-a-receiver-bound-to-application-header-x-match-expression/54998863

**Comment by k-wall** [comment]
> @k-wall I tried JMS filters (example here on rhea repo) and they work fine with Qpid Broker-J but using "amq.topic" exchange instead of "amq.match" (so strange)

@beaver71  The exchange concept comes from the old pre-AMQP 1.0 world (AMQP 0-x). It was those specifications that defined the behaviour of how instances of the in-built exchange types worked.  amq.match (which is an instance of the "header" exchange type) was never defined as understanding message selectors.   The exchange concept does not exist in AMQP 1.0 so you won't find the concept in other AMQP providers.  Apache Qpid did this to help is legacy user move to the new world.

I generally encourage message users to utilise the standard messaging features when building their applications.  So I echo @grs comments to use message selectors if you can for your use-case.
