### ISSUE TITLE
Plain text encoding to RabbitMQ

### ISSUE THREAD

**Issue by setheen** [amqp/rhea#206]
How does one publish plain text messages for RabbitMQ?

Using Rhea and the AMQP 1.0 [plugin](https://github.com/rabbitmq/rabbitmq-amqp1.0) for RabbitMQ, it seems published messages arrive to queues base64 encoded with header info prefixed to the value.  When viewed within the Rabbit management UI, one can see the message has arrived with a property similar to the following:
```
headers: | x-amqp-1.0-properties:Not UTF-8, base64 is: AFNz0....
```

and a payload similar to the following:
```
AFN3oQR0ZXN0
```
That payload contains the original message body "test" but also what I'm assuming to be header info as prefixed.  In contrast, using the amqpnetlite library, one can successfully deliver a plain text message creating a message as such:
```
var message = new Message{BodySection = new Data {Binary = Encoding.UTF8.GetBytes("test")}};
```

Delivering a message to the queue as plain text is important for the Rabbit broker as it would permit a slow transition scenario for 0.9.1 to 1.0 clients without introducing what I'll ignorantly refer to as 1.0 protocol encoding to the message bodies.

**Comment by grs** [comment]
try something like this:

```
sender.send({body:amqp_message.data_section(Buffer.from('hello world!', 'utf8'))});
```
That should be equivalent to the amqpnetlite message above.

**Comment by setheen** [comment]
Thank you very much @grs!  Submitted a PR to help others that may have similar questions
