### ISSUE TITLE
Long Running Senders and Azure Service Bus

### ISSUE THREAD

**Issue by ChuckLangford** [amqp/rhea#211]
I'm switching a project over to rhea and I currently have a connection and one sender. Connecting and sending work fine. The problem begins after 10 minutes of idle time; Service Bus disconnects me and the process crashes.

Reading through the docs, it seems like I should be able to configure rhea to reconnect automatically but I've so far been unsuccessful.

What is the intended way to handle this scenario? Is rhea equipped to handle this for me with automatic reconnects? Or should I be coding to handle this myself?

**Comment by amarzavery** [comment]
Hi Chuck that is true. SB will disconnect  after idle time out to avoid DOS attack.

Have you tried the new service bus sdk . It also depends on rhea and does handle such problems for you.
You can find the sdk over [here](https://github.com/Azure/azure-sdk-for-js/blob/master/packages/@azure/servicebus/data-plane/README.md).

It will make things much easier for you.

**Comment by ChuckLangford** [comment]
Thanks Amar, I'll take a look at it in the morning. I'm still curious though, what is the intended way to handle this scenario with rhea? Handle it manually? Or is it something else I'm missing?

**Comment by amarzavery** [comment]
I think rhea would automatically reconnect the amqp connection. I am not sure if it reconnects the sender/receiver links after establishing the connection once again. 

In the service bus sdk we manually reconnect the connection and everything on top of it.

**Comment by grs** [comment]
rhea does re-establish links on reconnect. However I believe for service-bus you need to do some special claims based authentication for links and rhea knows nothing about that, whereas the service bus sdk would take care of all that.

**Comment by ChuckLangford** [comment]
Thanks you two. I'll close this and try the service bus sdk tomorrow.
