### ISSUE TITLE
[Websocket]- Expose CloseEvent

### ISSUE THREAD

**Issue by k-wall** [amqp/rhea#216]
During websocket connection upgrade the AMQP server may determine that the connection should not continue and decide to terminate the connection by sending a close event [1].  For instance, the user may have insufficient privileges. 

The close event carries a code and reason.  Having this information available through the Rhea API would be useful for providing a clear error messages back to the user or for logging/diagnostics.

[1] https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent

(btw. I'd originally hoped to read the HTTP status code (403) for my use case.  I learnt from https://stackoverflow.com/questions/21762596/how-to-read-status-code-from-rejected-websocket-opening-handshake-with-javascrip that this wasn't possible).

**Comment by grs** [comment]
@k-wall, does this do it: https://github.com/amqp/rhea/pull/217 ? Should I think ensure the event is available through the error field of the context for the disconnected event.

**Comment by k-wall** [comment]
@grs all working well with the new release, thanks again.
