### ISSUE TITLE
how to transfer files using rhea? 

### ISSUE THREAD

**Issue by GaikwadPratik** [amqp/rhea#218]
This might sound a bit stupid, but I've a requirement. Is there a way to transfer file using `rhea` and `rhea-promise` over qpid? If so, can you point me to an example? Also is there any restriction on the size of the file?

**Comment by GaikwadPratik** [comment]
Awesome, Thanks. I was passing buffer, was confused if I had to wrap that in `binary` since it is originally binary.

You are as always quick to help!

**Comment by grs** [comment]
Actually you don't need that; as it is a buffer it will be encoded as an amqp binary payload by default anyway. You can just pass the buffer as the body and it should still work.

**Comment by GaikwadPratik** [comment]
perfect, let me try that...
