### ISSUE TITLE
disposition `delivery_failed` immediately redelivers message on same listener

### ISSUE THREAD

**Issue by GaikwadPratik** [amqp/rhea#221]
In our code, once the message is received by the receiver, we do some system checking.  If the system checks then amqp message is marked as `delivery_failed` using

```context.delivery!.modified({delivery_failed: true})```

but the message gets redelivered to the same listener instantaneously. 

1. Is this expected behavior?
2. Should there be any delay of the second delivery?
3. In a mulit-system situation, should the message be delivered on receiver of different system or it will be delivered to the same receiver on first system?

**Comment by grs** [comment]
What the broker does depends on the broker used and how it is configured. You can set 'undeliverable-here' to true if you do not want the message to be resent to the same consumer. However it is the broker that would then need to honour that request.
