### ISSUE TITLE
best practice for draining a queue

### ISSUE THREAD

**Issue by GaikwadPratik** [amqp/rhea#222]
Which of the following is the best practice for draining a queue?

1. create another receiver on the queue with source option set to ```distribution_mode: DistributionMode.move```
2. create another receiver with drain option as ``` context.receiver.drain = true;``` as shown [in this example](https://github.com/amqp/rhea/blob/master/examples/drain.js)

**Comment by grs** [comment]
The distribution mode will implicitly be move anyway for a queue, so 1. is not needed. The drain option gives the receiving client a way to determine if/when there are no more messages on the queue (rather than just timing out).

**Comment by GaikwadPratik** [comment]
Thanks!!!

**Comment by GaikwadPratik** [comment]
@grs I've reopened this issue since `DistributionMode` object wasn't explicitly exposed in the library. I've created a PR to fix this. Can you please have a look?

**Comment by grs** [comment]
The issue as described does not seem related to whatever issue you have using DistributionMode from typescript. (The distribution mode is not related to draining at all).

As mentioned on the PR the additional typescript definitions already define an enumeration for the distribution mode. If there is some issue in using that please raise an issue that more clearly describes the problem experienced.

**Comment by GaikwadPratik** [comment]
okay
