### ISSUE TITLE
Question: Examples on options for when autoaccept=false

### ISSUE THREAD

**Issue by kbfirebreather** [amqp/rhea#226]
The docs https://github.com/amqp/rhea#open_receiveraddressoptions indicate an option to disable autoaccept. I can't seem to find any documentation / examples on how to handle acknowledging the message, or any other responses for the consumer anywhere, along with any options the methods may accept. Does that exist anywhere?

**Comment by grs** [comment]
@kbfirebreather does https://github.com/amqp/rhea/blob/0537936f282bdcb7805f4d170280adc36fd5bc27/README.md help?

**Comment by kbfirebreather** [comment]
Yes, very much! Although it looks like you may have inverted the documentation on modified and released? I've been trying to go through the source to understand some things and saw this: https://github.com/amqp/rhea/blob/master/lib/message.js#L284

**Comment by grs** [comment]
The release method will actually double as modified, i.e. if you pass no arguments it will send back a released, if you do it will send back a modified.

The reason for this was to avoid people having to deal with the oddly named and unfamiliar concept of modified from the amqp spec (but leave modified there for those who know the spec). You can with the more familiar accept/reject/release.

**Comment by kbfirebreather** [comment]
Ah, good to know!
