### ISSUE TITLE
When does the sender credit increases?

### ISSUE THREAD

**Issue by Gadi-Manor** [amqp/rhea#228]
I'm sending messages to a queue with `snd_settle_mode=1`. 
When I send it 'slowly' I see that when the credit is below `300` then `Sender.on_flow` is called and the credit increases with ~700. 
However, when the messages are on a higher rate the credit reaches `0` before `Sender.on_flow` is called which leads to send failures.

**Comment by grs** [comment]
Credit is issued by the receiver, so in your case the broker that you are using. You should check whether the sender is senable before sending (esp if sending lots of messages). There is also a 'sendable' event that you can use to trigger the sending. That way the receiver (i.e. the broker) can control the flow of messages (which is the purpose of the credit scheme).

**Comment by Gadi-Manor** [comment]
Thanks.
