### ISSUE TITLE
positive and negative numbers are sent as unsigned or signed numbers

### ISSUE THREAD

**Issue by GaikwadPratik** [amqp/rhea#231]
@grs ,

I am trying to write a receiver using [AmqpNetLite](https://github.com/Azure/amqpnetlite). It works fine for string, bool values. However it is giving me trouble with numbers.

When I am sending positive numbers, they are marked as `uint`
```
{ test: 1}
```

When I am sending negative numbers, they are marked as `int`
```
{ test: -1.1 }
```
Special case, when I am sending `1.0`, it is being converted to either `uint` or `int` depending on above cases but in either case, it is sent as `1` instead of `1.0`
```
{ test: 1.0 }
```
Is this intended or is there any other generic way to send all the values as signed variables? and not convert double to int?

**Comment by grs** [comment]
If you want full control over the encoding, you can use the wrap_xxx methods from rhea.types, e.g. 

```
var rhea = require('rhea');
//...
var o = {foo:rhea.types.wrap_int(1),bar:rhea.types.wrap_double(1.0)}
```

**Comment by GaikwadPratik** [comment]
Thanks, 

That works splendidly. Is there any particular reason this isn't done at core level when message is wrapped in `message.js`?

**Comment by grs** [comment]
You want 1 encoded as an int. Others might want it encoded as a uint. The library cannot anticipate all desires. At present it will encode a numeric value as uint if it can. If it is a negative value, too large for a uint or not an integer then an appropriate alternative type will be chosen.

I accept that won't fit every use case, but nothing will. The types expose allow full control where necessary.

**Comment by GaikwadPratik** [comment]
make sense. Then one last question on this, is there any specific reason for converting numeric values to `uint` instead of `signed int`?

**Comment by grs** [comment]
No. I would argue neither is more correct than the other. However it has to choose one and I chose to go to unit where possible by default.

**Comment by GaikwadPratik** [comment]
:)
