### ISSUE TITLE
How to know which message was accepted?

### ISSUE THREAD

**Issue by andrealmeidap** [amqp/rhea#239]
Hello everybody,

I need to know which message was accepted when an event was raised, but the context only gives me the delivery object, in which I could not find in an easy way which message was accepted. I noticed the the data field in the delivery object maybe has the body of the message on it, but I could not figure out how to "decode" this field. Is there an easier way to know it?

Thanks in advance!

**Comment by grs** [comment]
The send() method on a sender returns a delivery object. That is the same object that will be included in the context for the accepted (or released etc) event. The delivery has an id which is a sequential number. It also has a tag which is an arbitrary string which you can supply as the second argument to the send if desired (else it is autogenerated).

So either you can use the return value from the send to store some context against id or tag that you can then retrieve on handling accepted, or you can specify a tag as a key to you context as the second argument and then retrieve that from the delivery on the accepted event.
