### ISSUE TITLE
Receiving a connection_close event for no apparent reason

### ISSUE THREAD

**Issue by shantsimonian** [amqp/rhea#241]
I noticed that after some time, while a connection is open and being actively used, I'm receiving a `connection_close` event from the broker (ActiveMQ) and it doesn't reconnect from there. Any idea why this might be happening? I noticed that there is a Connection TTL setting for ActiveMQ, but considering that this is an active connection, I don't imagine that that is the cause.

Any help would be greatly appreciated!

**Comment by grs** [comment]
Is there an error in the close? Or anything in the broker logs? Might be worth asking on the activemq list.

**Comment by shantsimonian** [comment]
Thanks for the response; I'm setting up logging now (AmazonMQ) - will post back here if I find anything helpful.

**Comment by ps2goat** [comment]
I'm on AmazonMQ, as well.  I have experienced this and it seems to happen during the broker updates.  I have a cluster with 2 nodes, and expected the connection rollover to work (it does not).

I added code to emit a `SIGTERM` when I receive a `connection_error` event, and now I have access to the previous container's logs.

The message being logged is: `local-idle-timeout expired`
condition: `amqp:resource-limit-exceeded`

The original problem I had is that rhea says `committed to buffer, pending send` but the connection never repairs itself.

I likely need to update rhea to see if the issue remains, but wanted to see if this helps before I do the update.  I'm currently on rhea version 0.2.20, running on node:10-alpine image with docker, kubernetes, Amazon EKS with AmazonMQ.

**Comment by grs** [comment]
If a connection is explicitly closed with an error, rhea will not try to reconnect unless the error is considered 'non-fatal'. You can set the 'non_fatal_errors' option to include 'amqp:resource-limit-exceeded' (by default it only has 'amqp:connection:forced').

**Comment by ps2goat** [comment]
Thanks for the quick reply. I'll get my app updated and test this soon!

**Comment by grs** [comment]
The AMQP 1.0 spec defines some, but brokers can (in theory at least) invent their own so the list here is not exhaustive:

http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#type-error
