### ISSUE TITLE
Amqp connection drop sometimes and not reconnect.

### ISSUE THREAD

**Issue by isikhi** [amqp/rhea#242]
Hi, 
I use rhea/amqp with aws active mq. 
But sometimes the connection is broken for some unknown reason and is not reconnect. When I look at the links on the ActiveMQ page, there are over 50 links for creating a new rhea connection in each job.
Is there a setting related to the maximum number of connections? 
Do you know why this fail happen?
I will share last error on below line I ran on pm2 
> Amqp client disconnected { Error: getaddrinfo ENOTFOUND myhostadresscom:8883 myhostadress.com:8883:5671
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname:
   'myhostaddr
  host:
   'myhostaddr
  port: '5671' }

also; after that log i see
> { error:
   { ConnectionError: local-idle-timeout expired
     message: 'local-idle-timeout expired',
     name: 'ConnectionError',
     condition: 'amqp:resource-limit-exceeded',
     description: 'local-idle-timeout expired',
     connection:
      Connection {
....
...
..

`7|xyz  | Amqp client disconnected { Error: read EINVAL`
`7|xyz  |     at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'EINVAL', code: 'EINVAL', syscall: 'read' }`
`5|xyz  | Amqp client disconnected { Error: read EINVAL`
`5|xyz  |     at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'EINVAL', code: 'EINVAL', syscall: 'read' }`

**Comment by grs** [comment]
Are you creating links in a handler for connection_open? That event will happen every time you reconnect. However reconnect automatically re-establishes any active links. That could be the cuase of extra unexplained links. If you need to trigger creation from the first connection_open you can use EventEmitter.once() rather than EventEmotter.on().

**Comment by isikhi** [comment]
> Amqp client disconnected { Error: getaddrinfo ENOTFOUND myhostadresscom:8883 myhostadress.com:8883:5671
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname:
   'myhostaddr
  host:
   'myhostaddr
  port: '5671' }



also; after that log i see
> { error:
   { ConnectionError: local-idle-timeout expired
     message: 'local-idle-timeout expired',
     name: 'ConnectionError',
     condition: 'amqp:resource-limit-exceeded',
     description: 'local-idle-timeout expired',
     connection:
      Connection {
....
...
..

**Comment by isikhi** [comment]
@grs thank you for response but i have problem with disconnection not unexplained links(actually they are explaniable, they are my loggers and each logger create new rhea instance. ). Yeah maybe too much connection could be problem but If problem is this how would i handle a lot of connection with no disconnect? 
 
How would i handle a lot of connection with no disconnection ?
Also what is best practice each queue node?
Should i create new instance from rhea for each sub node? I use like below
```
topic.x.abc = new rhea(opts) 
topic.x.cde = new rhea(opts)
topic.y = new rhea
...
```

**Comment by grs** [comment]
I would look at the broker logs to see if there is any clue there as to why you are being disconnected. One possibility of course is flaky tcp connectivity. Maybe experiment with a very simple single connection, e.g. an example program, to see if that also experiences issues. The connection idle timeout suggests a missing heartbeat, so either a dead connection or one or other side not processing properly. On the node side you need to ensure that you don't block the event thread for any length of time to ensure that all events are processed in a timely manner.

**Comment by isikhi** [comment]
Hi @grs and others, 
I want to edit this situation, yes drop sometimes because of aws server properties...
That i was choosed AWS server is the smallest, and that connection setting is set to 1000, but supports up to max 100 connection. So when i was reach 100 connection their gonna be disconnect. So, my situation is solved right now but still have confisuing about best practice :)

**Comment by grs** [comment]
You can have multiple subscribers all on the same connection. In general I would say use a single connection to a broker unless you have a good reason not to.
