### ISSUE TITLE
Issue with setting credit_window on a receiver, and having the value respected

### ISSUE THREAD

**Issue by kbfirebreather** [amqp/rhea#243]
How can I limit at the session level how many messages will be sent to consumers simultaneously, until those messages are ack'd? I see in the receiver options you can limit it per receiver, but I was looking to do it globally for the connection as whole.

**Comment by grs** [comment]
You can't (the protocol doesn't provide any way to do that). You would have to set the receiver limit based on knowladge of how many receivers you have and what the aggregate limit for the session should be.

**Comment by kbfirebreather** [comment]
Thanks for the response, I tried setting a limit on the individual receiver, but it doesn't seem to be working. 

Logging my open_receiver object shows as such:
`
{ source: { address: 'jms.queue.responses.disposition' },                                                                                                                                                                                                                       autoaccept: false,                                                                                                                                                                                                                                                              credit_window: 15 }
`

But when I log my consumer getting messages before and after I acknowledge the messages, my counter goes way above 15. I was anticipating it getting to 15, and toggling back and forth between 15 and 14 until all the messages are processed.

Is there something else I need to do in conjunction with setting a credit_window?

Based on my lockfile, i'm on RHEA 1.0.7.

**Comment by grs** [comment]
At present the window is not tied to acknowledgement. Therefore you need to set the credit_window to 0, issue credit for the limit you want to set, e.g. receiver.add_credit(10), then add a credit whenever you acknowledge a message.

**Comment by kbfirebreather** [comment]
Ah okay, last question...I hope! Would need to add a credit if the message is released, rejected, or modified as well?

**Comment by grs** [comment]
Yes (I should have mentioned that). Whenever you deem the message to have been processed, add a credit to allow another delivery to be sent.
