### ISSUE TITLE
How to create a "multicast" queue type?

### ISSUE THREAD

**Issue by agent-0028** [amqp/rhea#251]
Having great fun using this lib in combination with `rhea-promise`.

We need so implement a pub/sub relationship with multiple subscribers receiving the same message. The chart near the top of this page says the way to do that is to specify "multicast" for the address.

https://activemq.apache.org/components/artemis/documentation/2.0.0/address-model.html

We are using Artemis for local development, and planning to deploy to AWS ActiveMQ.

I don't find `multicast` or `anycast` anywhere in your source code or documentation

It seems like perhaps `delivery_mode` of `copy` would get us the behavior we need, but no matter what we do with `delivery_mode` our queues are showing up listed as `anycast` Queue type in the Artemis web console.

What are we missing? Any help would be greatly appreciated!

**Comment by grs** [comment]
You want a source/target capability of 'topic', e.g. something like:

```
open_receiver({source:{address:'mytopic', capabilities:['topic']}})
```

**Comment by agent-0028** [comment]
Thank you so much for the quick reply!

That appears to be working. In my local environment I can see `multicast` as the queue type now. Doing a build now to test against Amazon ActiveMQ.

Does that need to be set in the sender and receiver options or just the receiver?

**Comment by grs** [comment]
It should be set in both to avoid odd behaviour when they attach in different order.

**Comment by agent-0028** [comment]
Sadly, this is working locally against Apache Artemis, but not working when we deploy and use AWS MQ.

I am trying to get down to what might be different between my local dev set up running Artemis in a container, from AWS ActiveMQ.

This is might not be an issue with your library, but understanding this a bit better might get us over this blocker.

These articles talk about special prefixes for producers and consumers:
https://aws.amazon.com/blogs/compute/migrating-from-rabbitmq-to-amazon-mq/
https://activemq.apache.org/virtual-destinations

Is your library doing anything specific when `capabilities:['topic']` is added that relate to these special addresses?

Do you have any experience where something like this would work against the Apache open source version of the ActiveMQ server but not work against AWS version? It appears that these special prefixes can be configured to whatever string you want to use, so they could be different between these two environments.

In our case, we have a horizontally scaled back end, so 3 instances of the same stateless server running in Kubernetes. We need for essentially identical receivers in these containers to be able to all receive messages sent once from another service.

The three receivers would each have different IDs, but the addresses are the same, they all execute the same code.

**Comment by grs** [comment]
ActiveMQ 5 will recognise an address starting with 'topic://' as a topic and you can configure artemis to do the same. I believe it does also recognise the capability so I am surprised that does not work for you.

**Comment by agent-0028** [comment]
Yeah, locally when we add the capability we can see that the consumers and addresses have type "multicast", and we are not using any special prefix in the addresses.

Locally, this is also working fine, I can run 2 or 3 instances of our app in different terminals and they all get the same message.

However, in our remote environments connected to AWS MQ, only one receiver gets the message.

**Comment by nmargaritis** [comment]
@agent-0028 have you tried setting the addresses for both receivers and senders directly to `topic://your_address_here` and not specifying the capabilities?

```
connection.open_sender({
            target: {
                address: 'topic://your_address_here',
                dynamic: false,
                durable: false,
                expiry_policy: 'never'
            },
            autosettle: true
        });
```

**Comment by agent-0028** [comment]
Hey folks! Thanks so much for the rapid replies.

Here is our progress so far. I am pretty sure that the `rhea` library is working as it should for us, but we have some other network or other issue in our deployed environments that is definitely still causing us pain.

We switched to using this Docker image for local development:
https://github.com/rmohr/docker-activemq

We were able to specify version `5.15.9`, which should match the version we are using in AWS MQ.

Once we did that, to answer your question @nmargaritis, the only way we can get Topics with multiple subscribers to work locally is indeed as you suggest, by putting the magic prefix `topic://` directly in the address. And, per @grs suggestion we are using that same address in the senders as well.

It does not appear that using `capabilities:['topic']` is honored by that exact version of ActiveMQ.

Our deployment situation is pretty complicated, so even though we have things working reliably in a local environment, we are having issue when we deploy to AWS. I don't really think this is a problem with your library but here's the quick summary in case anyone else in the world can benefit from our troubleshooting or perhaps has a solution.

We are deploying a Node.js `express` app in Kubernetes, with 3 back end containers that all need to subscribe to messages sent by a task running worker server. All the point to point queue based messaging seems OK, but we seem to have some intermittent issues with topic subscribers.

Sometimes we can get 2 out of 3 receivers working for a while For any given container that is having issue when we restart the container and start fresh, we are seeing connection refused from AWS MQ for new connections, or the subscription just doesn't show up in the AWS MQ management console.

Like I said, I don't think you all kind folks can help with this level of troubleshooting. If we figure out anything that would be useful for other people on AWS ActiveMQ I'll update this issue later.

**Comment by grs** [comment]
Are they durable subscriptions? Do you have access to the broker logs (and if so is there any errors or warnings in there)?

**Comment by agent-0028** [comment]
Wow, thanks again for the quick replies. Y'all are a credit to open source!

This relates to the last follow up questions from both @grs and @nmargaritis.

I am not 100% sure we are correctly creating durable subscribers.

Do you think that would help or cause issues in this case?

We JUST set up a tunnel and port forwarding so we can actually see the management console in AWS, that will help our troubleshooting a lot. We don't have logging turned on for the broker at the moment, so still kind of flying blind there. Will be adding Cloudwatch logs at some point.

FYI, we are actually using `rhea-promise` as the rest of our app uses Promises quite a bit, but I know most of the low level things are actually handled by `rhea`. From `rhea-promise` are using `connection.createReceiver()` and `connection.createAwaitableSender()`.

In all your examples, I see the `durable` field being put inside of the `target` or `source` object. But that did not appear to work for us, we have been playing with specifying it at the top level of the sender or receiver options. When I added that field inside of `target` and `source` it broke our local integration tests.

What we have at the moment looks like this for sender:
```
const senderOptions = {
    name: 'some_name',
    target: { address: 'topic://some_address' }
};
```

And like this for receiver:
```
const receiverOptions = {
    name: 'some_receiver',
    source: { address: 'topic://some_address' },
    autoaccept: false,
    durable: true,
    expiry_policy: 'never'
};
```

Questions that @nmargaritis example code, and the examples in this repo brought up.

1. What is with `durable: 2`? Looking at the source code, that appears to be a boolean, so `2` would be the same as `true` ;-) That is also in your example for pub/sub, we couldn't find any kind of enum that would give `2` some other meaning.

2. What does `dynamic: false` do for us?

3. If we wanted to create durable subscriptions would we put that on the sender side or the receiver side or both?

Thanks again for the quick answers!

**Comment by nmargaritis** [comment]
The truth is that from my observation as well; durable `true` and `2` appear to do the same (placing subscribers to Active Durable Topic Subscribers), I just used the `2` option since it was part of the examples.

> If we wanted to create durable subscriptions would we put that on the sender side or the receiver side or both?
You have to put it to the receivers end (subscriber), it does not matter for the sender. [This](https://activemq.apache.org/how-do-durable-queues-and-topics-work.html ) could prove handy for you to understand the concept.

> What does dynamic: false do for us?

I cant give you a direct answer for this, maybe @grs can assist. My understanding and observation has to do with that 

`If an AMQP Link is dynamic then a temporary queue will be created and either the remote source or remote target address will be set to the name of the temporary queue` 

so since we deal with topics, we have to set this to false in order for it to work. We want to connect to a topic not a temporary queue. Topics are the pub/sub equivalent. Topics have queues only if there are durable subscribers but that's managed via the durable flag, not the dynamic. Dynamic is meant to be used for agnostic direct connections that a queue is needed, topics are not direct connections (1:1), but rather follow the publisher and subscriber pattern. There  might be many. In direct connections with dynamic true you will have a queue for each direct connection.

**Comment by grs** [comment]
dynamic: false is redundant since that is the default. The durable option would need to be at the source level, but for a durable subscriber you also need the expiry_policy: 'never'. I'm not clear if you really want durable subscribers or not (i.e. if you want the subscription queues to remain even when the client is not connected). If you do, you need to ensure that you set the container id to be the same every time and use the same link name in order to reattach to the right subscription. Again, I'm not suggesting you need durable subscriptions (and if you don't they are more hassle than simple subscriptions).
 
Stepping back a bit though, what are the issues you are seeing?

**Comment by agent-0028** [comment]
Based on some experimentation last night, I can see we do not have durable subscribers working. For our app, I don't think it matters. At the moment these are just providing user feedback when a task starts and stops, so stale messages are not helpful to users. I was only asking in case somehow being durable is the only way we can get subscriptions to be stable long term.

The issue we are having is that locally our subscriptions seem to be working fine. When we deploy to AWS the subscriptions are failing in some non-deterministic way. A fresh deploy to a new environment had three out of three working as expected, the same code deployed to a lower environment had two out of three working, after the next deploy on that same environment, all three stopped working.

For the ones that don't work, the subscriptions are not visible in the ActiveMQ management console provided by AWS, and we see a bunch of messages being queued and never acked.

In some cases, when I restart the containers with the failed subscriptions I am getting a connection error. I will open a different issue to ask about checking for healthy connections.

Not sure it matters, but in the spirit of "keep it simple" and YAGNI, we have a singleton class that always uses one container, re-uses the same connection and we are not managing sessions in any way or implementing any kind of connection pool. We were unable to get the failover to work, so for now just bumped our AWS MQ servers down to single instance deployments.

All our senders are closed after the message is sent, but of course we don't close the connection since it is shared.

For the receivers (both topic and queue based) we are just setting up the events and never closing or doing anything else with the receiver, they just stay in memory as long as the server is up.

So fun!

Honestly, we have closed the original story and opened a bug to work on later, this doesn't have a critical impact on our app at the moment, but if I could find some small thing to change I might push one or two more commits ;-)

**Comment by agent-0028** [comment]
Thanks again for the quick replies! I am closing this for now, I'll re-open if I learn more.
