### ISSUE TITLE
How to check for connection health?

### ISSUE THREAD

**Issue by agent-0028** [amqp/rhea#252]
At the moment we have a simple class that is a singleton and we are re-using the same container and connection.

We had a health check end point that was making a new connection and closing it as a way to check connectivity, but that was adding a lot of noise to the logs, and we were seeing errors from AWS MQ.

Is there a field we can examine on a connection to know it is healthy without needing to actually send a message or open/close?

**Comment by grs** [comment]
the is_open() should return true if open and connected.

**Comment by grs** [comment]
you can also enable heartbeats by adding idle_time_out to the connect options, value is in millisecs, so e.g. 10000

**Comment by agent-0028** [comment]
Thanks, that is easy enough!
