### ISSUE TITLE
cluster mode  receiver is lost

### ISSUE THREAD

**Issue by dbit-xia** [amqp/rhea#254]
When MQ is in cluster mode, after retrying the second address successfully, the receiver is lost?  
not trigger receiver.on('receiver_open',()=>{})

```
connection.on('disconnected', function (context) {
    let {reconnecting,error} = context; 
    if (reconnecting){ 
            console.log('addReceiver');
            let receiver = connection.open_receiver('examples');
            receiver.on('receiver_open', () => {
                console.warn('receiver_open OK');  **//not print this line??**
            });
    }
});
```

Has anyone encountered it?

**Comment by grs** [comment]
There is a built in reconnect facility which will also restore any senders and receivers. This will not trigger for a connection error, unless the error is considered non-fatal. You can control which errors are non-fatal through the 'non_fatal_errors' option on connection or its parent container.

When handling the disconnected event, you are no longer connected. So unless the connection is successfully re-established, anything you attempt in that handler will not have any impact.

**Comment by dbit-xia** [comment]
I forked a copy and modified it to solve this problem.
https://github.com/dbit-xia/rhea/commit/ada9fb0c60a6a61b50bd55e9d5f5a1d09fa5d6f6

**Comment by dbit-xia** [comment]
@grs I think this is a bug, only the receiver created during the reconnection period will be lost.

At connection.js on('disconnected'), exists `this._disconnect(); ... setTimeout(()=>this.reconnect())`

**Comment by grs** [comment]
@dbit-xia Can you post a complete reproducer that shows behaviour you believe to be incorrect? (I don't believe your patch is correct, delaying the call to _disconnect() until the reconnection attempt leaves the endpoints in the wrong state).

**Comment by dbit-xia** [comment]
https://github.com/dbit-xia/rhea_test
I uploaded a git that can be used to reproduce this problem.

I am modifying this because I guess if the disconnect method will refuse some operations after the call, but the result is ok.
