### ISSUE TITLE
lib add some strange chars to message

### ISSUE THREAD

**Issue by Naimadnap** [amqp/rhea#256]
It's add `SpESsESw�` to each message that I try to send to queue

config
```
const connectOptions = {
    host: ****,
    port: 5671,
    ssl: true,
    transport: 'tls',
    username: '****',
    password: '****',
    connectTimeout: 5000,
};

container.once('sendable', function (context) {
  
    if (context.sender.sendable()) {
            context.sender.send({
                body: 'hello'
            });
        });
});
var connection = container.connect(connectOptions);
connection.open_sender('topic://example.example');
```

**Comment by grs** [comment]
I believe it is your broker that is responsible for that. The extra data is part of the AMQP 1.0 message. E.g. if using ActiveMQ5 perhaps it is configured to 'raw' mode: https://activemq.apache.org/amqp

**Comment by Naimadnap** [comment]
@grs thanks for quick response - but I'm not sure if its on broker site. 
I see in logs that for this kind of message the encoding is run 3 times
```
rhea:message Encoding section 1 of 3: Typed { type: TypeDesc { name: 'List0', typecode: 69, width: 0, category: 1, create: { [Function] typecode: 69 } }, value: [], descriptor: { [Number: 112] type: TypeDesc { name: 'SmallUlong', typecode: 83, width: 1, category: 1, read: [Function: read], write: [Function: write], create: [Object] }, value: 112 } } +0ms
  rhea:message Encoding section 2 of 3: Typed { type: TypeDesc { name: 'List0', typecode: 69, width: 0, category: 1, create: { [Function] typecode: 69 } }, value: [], descriptor: { [Number: 115] type: TypeDesc { name: 'SmallUlong', typecode: 83, width: 1, category: 1, read: [Function: read], write: [Function: write], create: [Object] }, value: 115 } } +3ms
  rhea:message Encoding section 3 of 3: Typed { type: TypeDesc { name: 'Str8', typecode: 161, width: 1, category: 2, encoding: 'utf8', create: { [Function] typecode: 161 } }, value: 'hello', descriptor: { [Number: 119] type: TypeDesc { name: 'SmallUlong', typecode: 83, width: 1, category: 1, read: [Function: read], write: [Function: write], create: [Object] }, value: 119 } } +1ms
  rhea:message encoded 18 bytes +1ms
```
if I delete iteretion from message.js line 296 the message looks like `Sw�hello` and I thing somewhere in the middle the lib add something to payload

**Comment by grs** [comment]
It is encoding three different sections -header, properties and body - as expected by for the AMQP 1.0 message encoding.

**Comment by Naimadnap** [comment]
could I disable this behaviour somehow? I don't need this "decorators"

**Comment by grs** [comment]
They are not decorators. They are a core part of the AMQP 1.0 protocol. The message is encoded in a well defined format so that receivers can parse it. If you are receiving it as AMQP then the library you are using for that should be able to give you just the part you care about (e.g. the body). If your broker is either not preserving the encoding or translating it to another protocol, then that would be a broker configuration issue.

**Comment by Abhishek150995** [comment]
> It's add `SpESsESw�` to each message that I try to send to queue
> 
> config
> 
> ```
> const connectOptions = {
>     host: ****,
>     port: 5671,
>     ssl: true,
>     transport: 'tls',
>     username: '****',
>     password: '****',
>     connectTimeout: 5000,
> };
> 
> container.once('sendable', function (context) {
>   
>     if (context.sender.sendable()) {
>             context.sender.send({
>                 body: 'hello'
>             });
>         });
> });
> var connection = container.connect(connectOptions);
> **connection.open_sender('topic://example.example');**
> ```

Are you trying to publish messages to an Exchange of "topic" type??

**Comment by Naimadnap** [comment]
@Abhishek150995 I have used another lib so the issue for me isn't relevant anymore
