### ISSUE TITLE
How do I republish an unwanted(unsatisfied) message from the consumer?

### ISSUE THREAD

**Issue by isikhi** [amqp/rhea#268]
Hi, there is a message whose content can be changed by the publisher.
My receiver wants to receive this message only if it has the corresponding payload. If there is no payload involved, it wants to queue again after a certain time. If amqp do this, how do I do that with amqp?

**Comment by isikhi** [comment]
We can add @Question labels. Thank you

**Comment by grs** [comment]
On the client side, you could either release or reject messages that don't match your requirements (though how those are handled is server dependent), or you could republish and consume it.

Personally I don't like either of those options. If your broker (assuming you are using a broker) supports selectors you could arrange for a header on the message to indicate the type of message and filter on that server side.

**Comment by isikhi** [comment]
Thank you @grs !
