### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by martppa** [amqp/rhea#271]
Hi everyone, first of all I want to thank you guys for rhea development and all the effort you put in it. The reason a raise this issue is that I have noted that just by instantiating rhea and connecting it to the message broker I get ~30mb of RAM consumption. Is it normal or may I have missed something in my config? I am developing a bunch of microservices and ~30mb each plus the service itself, it's a lot. Thank you.

**Comment by grs** [comment]
If that is the amount consumed by the process, then the bulk of it is likely the node runtime (e.g. compare with a node app that does nothing but e.g. wait on a timer and loads no extra modules).

**Comment by martppa** [comment]
Hi @grs Thanks for the quick response. I have created a file called rhea_test.js with the following contnet: 

`var container = require('rhea');
container.on('message', function (context) {
    console.log(context.message.body);
    context.connection.close();
});
container.once('sendable', function (context) {
    context.sender.send({body:'Hello World!'});
});
var connection = container.connect({
    transport: 'tls', 
    port: 5671, 
    host: "{HOST}",
    username: '{username}',
    password: '{password}'
});
connection.open_receiver('examples');
connection.open_sender('examples');`

By running this file using node and PM2, once I do monit the process I get ~32mb RAM used.

**Comment by grs** [comment]
That is not all from rhea though, a lot of it is the node runtime. For comparison run a process with no external modules loaded e.g. 

```
setInterval(function () {
    console.log('.');
}, 10000);
```

**Comment by martppa** [comment]
Ok, I ran it and got ~26mb, you are right. Thanks.
