### ISSUE TITLE
Plain initial response validation logic make a reference to an object (this.connection) that is undefined.

### ISSUE THREAD

**Issue by k-wall** [amqp/rhea#275]
`PlainServer.prototype.start` tries to validate that the initial response is correctly formed.  If the initial response is incorrectly formed, the intent of the code is to fail the SASL negotiation.  However, the code is flawed as the PlainServer object does not posses the connection.

https://github.com/amqp/rhea/blob/a2be64887c6363a4e7d451a5a4f58bb15b06aea6/lib/sasl.js#L60

**Comment by k-wall** [comment]
Maybe SaslServer.prototype.on_sasl_init should give the connection to the mechanism?  This would allow PlainServer's validation to work correctly, and suit any custom implementations rewritten in the same pattern.

```
        this.mechanism = saslctor();
        this.mechanism.connection = this.connection;

```
        this.mechanism.connection = this.connection;

**Comment by grs** [comment]
My instinct would be to replace that line with:
```
 return Promise.reject('Unexpected response in PLAIN, got ' + fields.length + ' fields, expected 3')
```

**Comment by k-wall** [comment]
I think that works and it keeps the information hiding tight.  I don't actually need the connection object in my custom SASL implementation.

**Comment by grs** [comment]
Do you have a way to easily test this? (I would need to add some mangled implementation which will take more time) https://github.com/amqp/rhea/pull/276

**Comment by k-wall** [comment]
@grs will do

**Comment by k-wall** [comment]
I am testing with sasl_plain_server.js with a client mangled to send an PLAIN response with too many fields.  It is functional, but I see a promise waring 

node:9947) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9947) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by grs** [comment]
If you run with --unhandled-rejections=strict do you get a helpful stack trace? (The obvious place is handling the rejection, so it must be something less obvious, at least to me).

**Comment by grs** [comment]
The reason for the UnhandledPromiseRejectionWarning is that the handling now triggers an connection_error event on the connection, which if unhandled is then propagated back up to the container and if unhandled there triggers an error event and if that is not handled it throws. As the throw is in the catch() of the Promise it is treated as an unhandled promise rejection.

It can be avoided by handling the error in the sasl_plain_server.js example, but admittedly the log message doesn't make it immediately obvious that this is the problem. I've improved the fix by catching the uncaught error and logging it as such. If the connection_error or error event is handled, this isn't logged, if it is not then the user gets a clearer message about what is wrong.

**Comment by k-wall** [comment]
thanks @grs, that explanation makes sense.
