### ISSUE TITLE
[HELP] sending duplicated messages

### ISSUE THREAD

**Issue by natome** [amqp/rhea#277]
I am not very experienced at this lib, and meet one issue of sending duplicated messages. In brief, my first call is to send one message like `aaa` and my second call is to send another message like `bbb`. However, the second send both `aaa` and `bbb` but the first call has send `aaa`.

Here are details:
I am writing one simple message sender to ActiveMQ queue. It looks like this:
```javascript
module.exports = (buildId) => {
    var args = {
        'username': 'admin',
        'password': 'admin',
        'host': 'localhost',
        'port': 5672,
        'queue': 'queue://pipeline'
    };

    container.options.username = args.username;
    container.options.password = args.password;

    var connection = container.connect({
        host: args.host,
        port: args.port
    });
    var sender = connection.open_sender(args.queue);

    container.on('connection_open', function (context) {
        console.log('authenticated!');
    });
    container.on('sendable', function (context) {
        console.log('sent ' + buildId + '!');
        // when buildId = 999, then AciveMQ will get: 999
        context.sender.send({ body: buildId })
    });
    container.on('accepted', function (context) {
        console.log('accepted!');
        context.connection.close();
        console.log('disconnected!');
    });
}
```
When I write another script like this to test it:
```javascript
const touchMQ = require('touch-mq')
setTimeout(() => { touchMQ(111) }, 1000);
setTimeout(() => { touchMQ(333) }, 3000);
```
I get following logs
```
authenticated!
sent 111!    
accepted!    
disconnected!

authenticated!
authenticated!
sent 111!
sent 333!
accepted!
disconnected!
accepted!
disconnected!
accepted!
disconnected!
accepted!
disconnected!
```
Meanwhile, I checked the ActiveMQ dashboard. It says that 3 messages in total received. The first one is `111` and the following ones are `111` and `333`. Here `111` are duplicated messages.

Why it happens and what should I do to avoid this thing happening? Thanks!

**Comment by grs** [comment]
Your container is probably a module level variable, so you want to set your handlers on the connection. I.e. ```connection.on('sendable',...)``` etc

**Comment by natome** [comment]
It works! Thanks! @grs
