### ISSUE TITLE
Question: Is it possible to automatically remove (cancel) a request on a given queue

### ISSUE THREAD

**Issue by kbfirebreather** [amqp/rhea#280]
If I instantiate a request to a given queue with a correlation_id, then want to cancel that request. (Consumer is processing only one request at a time, so requests can pile up). Is there a built in hook to cancel a message on a queue with a given correlation id, or do I need to spin up a consumer, find the request and ack() it?

**Comment by grs** [comment]
That would depend on the broker. There is nothing in the AMQP protocol that would let you remove a message (except as you say by consuming then accepting).

**Comment by kbfirebreather** [comment]
Okay, thought so, but wasn't entirely sure. Thanks for the response!

**Comment by grs** [comment]
One other thing is you can set a time to live (ttl) on the request, so if it is not delivered to the receiving client within the specified time it will get dropped.

**Comment by grs** [comment]
Or some brokers have a feature whereby a message can 'replace' another on n the queue based on some key.
