### ISSUE TITLE
Sender Status Check for Offline Queue

### ISSUE THREAD

**Issue by isikhi** [amqp/rhea#282]
Hi! Sometimes Amazon goes to shutdown the Active MQ servers and we cannot access a few minutes or hours... So when the server is down I want to create an offline queue (text based) and then when the connection reconnect i want the publish messages which is on offline queue.
So i have a publish method on my rhea class, this class
```
  publish(topic, durable, message) {
    const sender = this.rhea.open_sender({ target: { address: `tr.${topic}`, durable } });
    sender.on('sendable', () => {
      sender.send({ body: message });
    });
  }
```
sender.sendable() method only return true in sendable listener. i want to know the sender is connected or not before sender.on('sendable',()) method.
How would I do that? 
Also how would i check acknowledge of sender.send()

**Comment by grs** [comment]
The sender_open event will tell you that the sender has been opened on the remote side (i.e. the broker).

The accepted event will tell you when a message has been accepted. You can actually send a message even when the sender is not sendable(), and it will be buffered until there is credit. However you don't want to do that for any volume of messages or the memory will build up.

(Not sure if I am answering your question here?)

**Comment by isikhi** [comment]
i only want publisher acknowledge information. if any error occured on publish method i want to write the message to offline queue json, then i will republish when the connection is okay. 
something like that,
```
let topic = 'xyz'
let message = 'message to publish'
try {
  amqp.publish(topic, 2, message) //should return ack
} catch (e) {
  amqp.writeOfflineQueue(topic, 2, message)
}
```

**Comment by grs** [comment]
You can look at reha-promise if you would like to use a promise style for this.

With rhea itself, you have to handle an event for that. One option is to handle 'accepted' one way and then 'released' and 'rejected' another way (these are two forms of negative acknowledgement from the broker).

The other option is to handle the 'settled' event and then check the remote_state with e.g. container.message.is_accepted(context.delivery.remote_state) or container.message.is_rejected(context.delivery.remote_state) etc

**Comment by isikhi** [comment]
Allright @grs  thank you. 
I dont know should i open new issue but I want to ask one another thing. Is it bug or not? 
> 
If the connection loss on the loop. When the connection is came all the messages on session reproduce. Is it normal?
I mean if i loop the publisher. and cut the connection middle of something, after the reconnection that will sent already sent previous connection. is it normal?

-> RabbitMQ On; connection is set; loop is start; for i = 0; i < 100; i++;
ok This 0 the important message!
ok This 1 the important message!
ok This 2 the important message!
ok This 3 the important message!

-> Cut the rabbit mq server connection.
-> Wait a few sec then re-open mq server 

ok This 0 the important message!
ok This 1 the important message!
ok This 2 the important message!
ok This 3 the important message!
ok This 4 the important message!
ok This 18 the important message!
ok This 19 the important message!
ok This 20 the important message!
.....
.....
.....
---- 
In my opinion the messages that sent on previous connection should not sent after reconnect. but they reproducing automaticly. is this a bug or expecting result?

**Comment by grs** [comment]
No, rhea does not automatically resend messages.

Are you sure you are not retriggering the loop on reconnection?

**Comment by isikhi** [comment]
All my class and test is below
````
const uuidv4 = require('uuid/v4');
const rhea = require('rhea');
const config = require('../config');

class Amqp {
  constructor(options = { container: null }) {
    this.options = {
      host: config.mq.host,
      port: config.mq.port,
      username: config.mq.username,
      password: config.mq.password,
      transport: config.mq.transport,
      containerId: uuidv4(options.container),
    };
  }

  connect() {
    let attempt = 0;
    const hosts = [config.mq.host, config.mq.hostOnFailOver];
    this.rhea = rhea.connect({
      host: this.options.host,
      port: this.options.port,
      username: this.options.username,
      password: this.options.password,
      transport: this.options.transport,
      container_id: this.options.containerId,
      connection_details() {
        const details = {
          host: hosts.length ? hosts[attempt % hosts.length] : hosts,
          port: config.mq.port,
          transport: config.mq.transport,
        };
        attempt += 1;
        return details;
      },
    });
    this.rhea.on('connection_open', () => {
      console.info('Amqp client connected');
    });
    this.rhea.on(
      'connection_error', async () => {
      console.warn('Conn error!');
    });
    this.rhea.on('disconnected', () => {
      console.warn('I am disconnected.');
    });
  }

  writeOfflineQueue(obj) {
    // console.log('CONN OFF!', obj.message); // that will be injected.
  }

  publish(topic, durable, message, callback) {
    const sender = this.rhea.open_sender({
      target: {
        address: `_${config.env}.${topic}`,
        durable,
      },
    });
    if (this.rhea.is_open()) {
      sender.on('sender_open', () => {
        sender.send({ body: message });
      });
    } else {
      this.writeOfflineQueue({
        topic,
        durable,
        message,
      });
    }
  }

  subscribe(topic, durable, callback) {
    let expiryPolicy = 'session-end';
    durable > 0 ? expiryPolicy = 'never' : expiryPolicy;
    const receiver = this.rhea.open_receiver({
      source: {
        durable,
        address: `_${config.env}.${topic}`,
        expiry_policy: expiryPolicy,
      },
    });
    receiver.on('message', (context) => {
      callback(context.message);
    });
  }

  close() {
    this.rhea.close();
  }
}
async function runTestConnection() {
  const mqClient = new Amqp();
  await mqClient.connect();
  mqClient.subscribe('test', 1, (m) => {
    if (m) console.log('ok', m.body);
  });
  let i = 0;
  setInterval(() => {
    try {
      mqClient.publish('test', 1, `This ${i} the important message!`);
    } catch (e) {
      console.warn(e);
    }
    i++;
  }, 2000);
}
runTestConnection();

```

**Comment by grs** [comment]
Where you have:

```
      sender.on('sender_open', () => {
        sender.send({ body: message });
      });
```
That event, 'sender_open', will be emitted again when the connection reconnects and the sender is re-established, which will cause your code to resent the message.

As you are creating a new sender for every publish you should close the senders once the message has been accepted, meaning that they will not be recreated when the connection is re-established. However in the event that the connection fails before you have closed it, it will be re-established and so would trigger the event handler that sends the message.
