### ISSUE TITLE
A clear, commented example laying out best strategy for staying connected?

### ISSUE THREAD

**Issue by tony-gutierrez** [amqp/rhea#284]
It is unclear what is a good strategy for reconnecting. 

In my code I am monitoring the connection on a timer, and attempting to clear things like the receiver when needed, but it is really not clear what I need to worry about and what I dont when montoring all the different aspects of a connection (session, receivers, etc).

**Comment by grs** [comment]
From the perspective of automatic reconnection when underlying transport is lost, that should work be default with no monitoring required.

What is the motivation for clearing the receiver?

**Comment by tony-gutierrez** [comment]
I am connecting to an Azure Service bus, which means I need manual code to send a token to a $cbs topic upon reconnect. This code is a few years old, I added monitoring of the receiver at some point to try to fix a reconnect fail loop.

I am not sure if any of it makes great sense, but I don't really have anything to go off of that both does auto-reconnect, and has an event that can happen on connect.

**Comment by tony-gutierrez** [comment]
It is also unclear what the arguments are for each raised event? Is the argument always the current context? I based my code off some Microsoft code, and they lead me to believe that sometimes the argument is an error.

**Comment by tony-gutierrez** [comment]
I think I started monitoring the senders and receivers because:

1.  I connect

**Comment by tony-gutierrez** [comment]
I think I added the monitoring because:

1. I connect
2. I make cbs sender and receiver. 
3. I send cbs token. 
4. I make main reciever. 
5. I periodically send an updated token to cbs sender. 
6. On disconnect and reconnect, the main receiver has to be cleared out until the cbs transaction has taken place again.  Then it can be recreated.

**Comment by grs** [comment]
The cbs used by servicebus does indeed complicate the reconnect somewhat. There is a library that is designed for use with servicebus, not sure if that uses rhea's reconnect or reimplements something more tailored for servicebus.

**Comment by tony-gutierrez** [comment]
Thanks. I ended up just disabling reconnect and using my own timer. That way I can just clear the connection and re-execute the hard coded connect sequence.
