### ISSUE TITLE
Uncaught Exception at: undefined   error: TypeError: Cannot read property '_process' of undefined

### ISSUE THREAD

**Issue by frabbidgdean** [amqp/rhea#286]
Our project is using Azure service-bus and it is running into this uncaught exception which we have not faced before:

msg: Uncaught Exception at: undefined 
 error: TypeError: Cannot read property '_process' of undefined
    at Connection._process (/app/node_modules/rhea/lib/connection.js:687:39)
    at process._tickCallback (internal/process/next_tick.js:61:11)

Node version: v10.16.3
rhea version: 1.0.12
Azure version: 2.3.1-preview

**Comment by grs** [comment]
Was this preceded by any other errors, e.g. 'Invalid value for remote channel'? Is it reproducible?

**Comment by frabbidgdean** [comment]
> Was this preceded by any other errors, e.g. 'Invalid value for remote channel'? Is it reproducible?

The error was not preceded by any other errors. Also, we were not able to reproduce this error in our local environment. We only saw it in our prod environment.
