### ISSUE TITLE
Subscribe Topic with filter

### ISSUE THREAD

**Issue by sragneau** [amqp/rhea#288]
Dear community,

I'd like to create subcription with my only one topic called Topic1.

In the server side i write that 
`    
context.connection.open_receiver({source:{address:'topic://topic1', filter:{'subject':amqp_types.wrap_described('test', 0x468C00000001)}}});
`

But when i send message 
`
var sender = connection.open_sender('topic://topic1');
sender.on('sendable', function(context) {
    sender.send({body:"Test d'un message", subject:'test2'});
    connection.close();
});
`
The server receive the message when he shouldn't

One other thing, i can see that somes users wirte amp.topic to create topic. When i try, a new queue is created called amp.topic.

**Comment by grs** [comment]
See here for an example of setting a filter: https://github.com/amqp/rhea/blob/master/examples/selector/recv.js#L44

Broker's all have their own behaviours around how (or if) queues and/or topics are created 'on demand' (i.e. in response to a sender or receiver being created). The topic:// prefix is I believe a default for activemq5. Other broker's may be able to be configured to recognise that as a topic. Another approach used is the use of a 'capability' in the source or target whose value is 'queue' or 'topic'. Look at your brokers documentation for more information there.
