### ISSUE TITLE
Multiple instance of subscription

### ISSUE THREAD

**Issue by sragneau** [amqp/rhea#289]
When we create multiple instances of our application each instance receive the message.
Our aim is, the first instance must receive and others nothing.

Could you create a queue and binding it to an subscription ?

**Comment by grs** [comment]
That depends on the broker you use. Many brokers offer shared subscriptions whereby the messages are shared out between the consumers on that shared subscription. That doesn't sound like what you want however. You want the same consumer to get all the messages (the others are then presumably there only in case that first consumer fails? Is this an attempt to reduce the outage for a failed and restarted consumer?).

I would figure out what the feature on the broker you are using is and then if needed ask how to invoke or access that feature through the client.

**Comment by sragneau** [comment]
Yes you understand what we want. We can imagine also an rotation with application when the broker send the message. app1, app2, app1, app2.
We're working with aws mq (ActiveMQ5), I found some information with vitual topic but i don't know how to create it.

**Comment by grs** [comment]
I would ask on the activemq user list about how to configure what you want and whether there is anything specific that needs to be done to subscribe to such a virtual topic over AMQP.

**Comment by Drew-Kimberly** [comment]
Hunting down information in this issue queue and stumbled on this. @sragneau I've accumulated quite a bit of knowledge on activemq so perhaps I can help:

With VirtualTopics in ActiveMQ, first note the discrepancy between sending/receiving messages; you send a message to the topic (`topic://VirtualTopic.foo` in conventional AMQ naming) but you subscribe from the topic indirectly via a queue (`queue://Consumer.{$CLIENT_NAME}.{$CONSUMER_NAME}.VirtualTopic.foo` in conventional AMQ naming). By doing this you can achieve the following consumer behaviors:

If multiple consumer threads/processes share the same `$CONSUMER_NAME`, messages will be load-balanced among the processes, i.e. app1, app2, app1, app2, etc...

If multiple consumer threads/processes each use different `$CONSUMER_NAME` values, messages will be simultaneously delivered to _each_ process, i.e. app1 and app2 receive message_1.

Given multiple consumer threads/processes share the same `$CONSUMER_NAME` it is also relatively straightforward to achieve the behavior where the 1st process to establish a session w/ the broker receives _all_ messages. When that 1st process disconnects, the 2nd process to establish a session w/ the broker receives all messages, and so on (i.e. app1, app1, app1, *app1 disconnects*, app2, app2, app2, etc). To achieve this, you must use message groups: https://activemq.apache.org/message-groups when producing messages. In AMQP 1.0, this equates to the `group-id` message header field.

Hope this helps!

**Comment by grs** [comment]
Thanks for the information @Drew-Kimberly !

**Comment by sragneau** [comment]
Thx virtual topic works

**Comment by saurabhwl** [comment]
Thx for explaining the virtual topic naming convention! It worked!
