### ISSUE TITLE
Session Examples 

### ISSUE THREAD

**Issue by sragneau** [amqp/rhea#290]
Hi, 

Is there any example with session object.
I need to create session to close a link.

I tried like that no queue are created :

```
if (!this.context().global.awsConnection) {
                this.context().global.awsConnection = container.connect({
                    host: process.env.APP_AMQ_HOST 
                    port: '5671',
                    transport: 'tls',
                    username: process.env.APP_AMQ_USER 
                    password: process.env.APP_AMQ_PWD
                })
            }

            if (!node.receiver || !node.session) {

                node.session = node.context().global.awsConnection.create_session();
                //console.log('session', node.session);

                console.log('open receiver');
                node.receiver = node.session.open_receiver({
                    name: n.name || 'name-receiver-a',
                    source: {
                        address: 'Consumer.' + n.name + '.VirtualTopic.' + n.topic,
                        //durable: 2,
                        //expiry_policy: '',
                        filter: filters.selector("objectType='" + n.filter + "'")
                    }
                });

```

Session is marked as closed

**Comment by grs** [comment]
You need to call open() on any newly created session.

**Comment by sragneau** [comment]
Ok great now i can see the queue.
But i cannot now receive message since i use session. 
Without session that's works.


`
if (!node.sender) {
                node.session = node.context().global.awsConnection.create_session();
                node.session.open();
                node.sender = node.session.open_sender('topic://VirtualTopic.' + n.topic);
            }
            console.log('on envoie un msg')
            node.sender.send({
                body: msg.payload,
                application_properties: {
                    objectType: msg.filter || n.filter
                }
            });


`

**Comment by grs** [comment]
The session you use should have no impact on how the link is handled. You should not need to explicitly create a session anyway tbh, but if you do it should have no effect on how the broker treats the message sent over it.

It is not really possible to tell what is going on from small snippets of your code I'm afraid.

**Comment by sragneau** [comment]
Ok it was a code issue.
