### ISSUE TITLE
ActiveMQ: Strange characters in the beginning of messages

### ISSUE THREAD

**Issue by gerasyana** [amqp/rhea#292]
Hey.

I send XML messages to ActiveMQ message broker and noticed that all messages contain some strange characters at the beginning. See code below:

```
const sender = this.connection.open_sender(this.config.outQueue);
sender.send({ body : xml })
```

Message example from message broker:

```
SpESsESw�y<?xml version="1.0" encoding="UTF-8"?>
<pbx:photobox>
  ........
</pbx:photobox>
```

Ho to fix it? Should I need to set some extra options?

**Comment by grs** [comment]
Where are you seeing that message? Is it from a consumer, of so which client library is that consumer using?

It is in any case a broker side issue. My first guess is that it is a result of the 'native' mapping default (https://activemq.apache.org/amqp ).

**Comment by gerasyana** [comment]
I have access to the message through ActiveMq Web Console. 

Previously we sent messages from .NET app to the broker and didn't face the issue.

**Comment by grs** [comment]
What library is the .NET app using? It sounds to me like the web console is showing messages using the 'native' mapping (i.e. the full amqp message encoding is included in the message body). If you change the mapping to jms it should look better.

**Comment by gerasyana** [comment]
We use Apache.NMS.ActiveMQ library. 

I will ask a client to change the mapping to JMS and check if it fixes the issue.

**Comment by grs** [comment]
NMS uses openwire - i.e. ActiveMQ's 'native' protocol - so that is why the AMQP mapping does not apply to those messages.

**Comment by DanilaFadeev** [comment]
@grs Does it mean that rhea.js doesn't use native AMQP protocol and this problem could be fixed only on ActiveMQ's setup side?
And also, is this issue affect the data we store on a broker, or it just a display specific?

**Comment by grs** [comment]
No, rhea *does* use fully compliant AMQP. However AMQP is not the 'native' protocol of the ActiveMQ broker (that is OpenWire), and by default it seems the whole AMQP message (i.e. the AMQP headers, properties etc as well as body) is included as the body of the message in ActiveMQ. I believe if you change the mapping to jms you will see a more natural mapping of AMQP in the broker.

**Comment by gerasyana** [comment]
Ok got it. I will ask a client to change the mapping
