### ISSUE TITLE
TLS 1.3 support

### ISSUE THREAD

**Issue by beaver71** [amqp/rhea#295]
I'm trying to use this library to develop a client which should connect to an ActiveMQ instance configured for TLS 1.3 (this is a mandatory requirement in my project).
My simple client is derived from the [tls_client.js example](https://github.com/amqp/rhea/blob/master/examples/tls/tls_client.js).
When trying to connect the client goes immediately to disconnect event without any error message.

On broker side I see in the log file:

`2020-04-28 14:00:29,882 | WARN  | Transport Connection to: tcp://x.y.z.k:52069 failed: javax.net.ssl.SSLHandshakeException: Client requested protocol TLSv1.2 is not enabled or supported in server context | org.apache.activemq.broker.TransportConnection.Transport | ActiveMQ Transport: ssl:///x.y.z.k:52069`

So I infer that only TLS 1.2 is supported in rhea...
Is that correct? Are there plans to support TLS 1.3?

**Comment by grs** [comment]
The TLS support comes from the underlying node.js runtime (or from the browser if running there). For node v12 and above I think 1.3 is enabled by default. What version are you running? On 10 and 11 I believe you can specify --tls-max-v1.3 to the interpreter.

**Comment by beaver71** [comment]
thanks a lot, I'm verifying with node.js runtime.
