### ISSUE TITLE
Example on transactional messaging

### ISSUE THREAD

**Issue by thomasaelbrecht** [amqp/rhea#296]
Is it possible to add an example on how to implement transactional messaging? For as far as I know, I can't find anything about this in the docs. I've read through the chapter about transactions in the protocol specification but I don't really see how to implement this. I'm using ActiveMQ as message broker. Anyone who can help me? (I'm fairly new to AMQP...)

**Comment by anuragphadnis** [comment]
Did you implement it yourself? If yes can you please add a comment explaining the steps.

**Comment by anuragphadnis** [comment]
> Is it possible to add an example on how to implement transactional messaging? For as far as I know, I can't find anything about this in the docs. I've read through the chapter about transactions in the protocol specification but I don't really see how to implement this. I'm using ActiveMQ as message broker. Anyone who can help me? (I'm fairly new to AMQP...)

Did you implement it yourself? If yes can you please add a comment explaining the steps.

**Comment by thomasaelbrecht** [comment]
No, unfortunately I didn't implement it myself... I can't help you with it.
