### ISSUE TITLE
I want to publish in messages to a Exchange of "Topic" type. How to publish to the exchange with the "routing key"?

### ISSUE THREAD

**Issue by Abhishek150995** [amqp/rhea#297]

**Comment by grs** [comment]
The 'routing key' is an AMQP 0.10 concept that did not make it into 1.0. This library supports only AMQP 1.0. Check with your broker whethe rthey support 1.0 and if so how the routing key is mapped to that protocol (probably the address or subject).

**Comment by Abhishek150995** [comment]
I am using RabbitMQ broker that support AMQP 1.0 with additional plugin.

To publish to a "fanout"exchange is was able to use rhea library. 
context.connection.open_sender('/exchange/ExchangeName');

But when i want to open a sender with "topic" exchange. It is throwing an error 

Error Occured :{function_clause,[{rabbit_exchange_type_topic,split_topic_key,[undefined,[],[]],[{file,[115,114,99,47,114,97,98,98,105,116,95,101,120,99,104,97,110,103,101,95,116,121,112,101,95,116,111,112,105,99,46,101,114,108]},{line,268}]},{rabbit_exchange_type_topic,'-route/2-lc$^0/1-0-',2,[{file,[115,114,99,47,114,97,98,98,105,116,95,101,120,99,104,97,110,103,101,95,116,121,112,101,95,116,111,112,105,99,46,101,114,108]},{line,50}]},{rabbit_exchange_type_topic,route,2,[{file,[115,114,99,47,114,97,98,98,105,116,95,101,120,99,104,97,110,103,101,95,116,121,112,101,95,116,111,112,105,99,46,101,114,108]},{line,52}]},{rabbit_exchange,route1,3,[{file,[115,114,99,47,114,97,98,98,105,116,95,101,120,99,104,97,110,103,101,46,101,114,108]},{line,416}]},{rabbit_exchange,route,2,[{file,[115,114,99,47,114,97,98,98,105,116,95,101,120,99,104,97,110,103,101,46,101,114,108]},{line,406}]},{rabbit_channel,handle_method,3,[{file,[115,114,99,47,114,97,98,98,105,116,95,99,104,97,110,110,101,108,46,101,114,108]},{line,1356}]},{rabbit_channel,handle_cast,2,[{file,[115,114,99,47,114,97,98,98,105,116,95,99,104,97,110,110,101,108,46,101,114,108]},{line,627}]},{gen_server2,handle_msg,2,[{file,[115,114,99,47,103,101,110,95,115,101,114,118,101,114,50,46,101,114,108]},{line,1067}]}]} 

Why is it so? why cannot i connect to an exchange of "topic" type when "fanout" type works fine

**Comment by grs** [comment]
From https://github.com/rabbitmq/rabbitmq-amqp1.0#routing-and-addressing, I would suggest using /exchange/<exchange-name./<routing-key> as the address for the sender when using a topic exchange (or a direct exchange, i.e.any exchange that requires the routing key).

**Comment by Abhishek150995** [comment]
> From https://github.com/rabbitmq/rabbitmq-amqp1.0#routing-and-addressing, I would suggest using /exchange/<exchange-name./ as the address for the sender when using a topic exchange (or a direct exchange, i.e.any exchange that requires the routing key).

Thanks for the reply, but does rhea library allow to publish with "subject" analogous to "routing key" in prior versions

I tried using context.connection.open_sender('/exchange/ExchangeName/');
but it throws same error

**Comment by grs** [comment]
My apologies, the markdown processing swallowed part of the address. Try ```/exchange/<exchange-name>/<routing-key>```. However you can certainly also send a subject in the message (just specify a subject field in the message object you send e.g. ```{subject:'foo',body:...}```

**Comment by Abhishek150995** [comment]
Thanks for the quick response. But i had a query as there may be multiple routing keys. What is the relation between routing key and subject. 
 According to my understanding.. routing key and subject are the same

**Comment by Abhishek150995** [comment]
> My apologies, the markdown processing swallowed part of the address. Try `/exchange/<exchange-name>/<routing-key>`. However you can certainly also send a subject in the message (just specify a subject field in the message object you send e.g. `{subject:'foo',body:...}`

Does rhea library has the functionality to create an Exchange and bind queue to the exchange using functions.. Currently i am creating the Exchange using the UI of RabbitMQ

**Comment by grs** [comment]
In AMQP 1.0, there is no such thing as 'routing key'. From the description linked to above, the RabbitMQ broker maps the 1.0 subject to the routing key if it was not specified in the address.

AMQP 1.0 also has no notion of exchanges or bindings, so you cannot directly control binding on RabbitMQ. From the same document, you can subscribe to ```/topic/<routing-key>``` and the broker will automatically create and bind a temporary queue.

**Comment by Abhishek150995** [comment]
> In AMQP 1.0, there is no such thing as 'routing key'. From the description linked to above, the RabbitMQ broker maps the 1.0 subject to the routing key if it was not specified in the address.
> 
> AMQP 1.0 also has no notion of exchanges or bindings, so you cannot directly control binding on RabbitMQ. From the same document, you can subscribe to `/topic/<routing-key>` and the broker will automatically create and bind a temporary queue.

Okay I understood that there is no such thing as 'routing key' in AMQP 1.0, 
But what is the significance of <routing-key> in the address open sender('/exchange/<exchange-name>/<routing-key>')

**Comment by grs** [comment]
It will be the routing key that is used for all messages sent on that sender. If you want to set that key per message, then set the subject on the message instead. But that is just the RabbitMQ broker's interpretation of the address.
