### ISSUE TITLE
Question: How to detect that a connection is being aborted due to idle timeout

### ISSUE THREAD

**Issue by chradek** [amqp/rhea#302]
Hi @grs 
We're encountering an issue in our library sometimes when the idle timeout for a connection is hit. When the rhea connection's `idle` method is invoked, it closes the local side of the connection, then closes the remote side of the connection after an additional 1000 ms:https://github.com/amqp/rhea/blob/1f4d279bbf05357df44a1d0a3ce962e9a95cdc1f/lib/connection.js#L572

We are performing reconnect logic in our library instead of relying on rhea right now. Our issue occurs when we attempt to reconnect during that 1000 ms period of time. We check if the connection is open (using [rhea-promise](https://github.com/amqp/rhea-promise/blob/b792d847ba5bb1adf7872aa49a6e1b779e46f754/lib/connection.ts#L395)) and then end up calling the rhea-promise connection.open (which calls rhea's connection.connect) method. This causes problems for some of our in-flight requests since this resets some of the remote state the rhea connection has.

It seems like checking that `isOpen() === false` and `isRemoteOpen() === true`, then waiting for a `disconnect` event on the connection before reopening a connection fixes the issue for us. Is it reasonable to assume that in this case, we should eventually see a disconnect event, or at least that the connection won't be brought back up (since we don't rely on rhea's reconnect?)

Alternatively, I noticed that the `abort_idle` connection property is set to true when `idle` is called, but this isn't part of the type definitions so I'm not sure this can be counted on as part of the public API.

**Comment by grs** [comment]
Yes, you should always receive a disconnect event and if reconnect is disabled, rhea will not try to reconnect.

The client first sends an AMQP close, just in case the connection is still active and peer has just not sent frames[1], however if it then ensures that if the socket is not closed by peer within a second, it does get closed by the client.


[1] 2.4.5 "If the threshold is exceeded, then a peer SHOULD try to gracefully close the connection using a close frame with an error explaining why. If the remote peer does not respond gracefully within a threshold to this, then the peer MAY close the TCP socket."

**Comment by chradek** [comment]
@grs, thank you for the quick response! That helped a lot and I can close this now.
