### ISSUE TITLE
How do you pronounce "rhea"?

### ISSUE THREAD

**Issue by robinzimmermann** [amqp/rhea#311]
Please settle a dispute between me and a colleague on the correct way to pronounce `rhea`.

Is it `ray-ah`, `ree-ah`, or something else?

Obviously, this is a SEV 1 issue...

**Comment by grs** [comment]
:-) I myself have been using the first of those... however it does look as though I may be wrong in that as https://en.wikipedia.org/wiki/Rhea_(bird) indicates the second one is correct.

Generally I would say it is the users prerogative!

**Comment by robinzimmermann** [comment]
I guess I'll have to switch to `ree-ah`. I had defaulted to `ray-ah`.

**Comment by robinzimmermann** [comment]
(Apologies if I wasn't supposed to close the ticket.)
