### ISSUE TITLE
Possible bug: reader.remaining is not used as a function in frames.js

### ISSUE THREAD

**Issue by richardpark-msft** [amqp/rhea#316]
I noticed this inconsistency with reader.remaining where it is used as a field and not called as function.

Here's the line that I believe is incorrect:
https://github.com/amqp/rhea/blob/5a94367cc0069de6f69f102f059a69e6ead55f45/lib/frames.js#L66

Within the same function it is called as a function:
https://github.com/amqp/rhea/blob/5a94367cc0069de6f69f102f059a69e6ead55f45/lib/frames.js#L86

And here's the definition that appears to support it being a function:
https://github.com/amqp/rhea/blob/5a94367cc0069de6f69f102f059a69e6ead55f45/lib/types.js#L692

**Comment by grs** [comment]
@richardpark-msft Thanks and well spotted! I have fixed in https://github.com/amqp/rhea/commit/d0a6bff78c633f9c46a87fe259166aafca90b48b.
