### ISSUE TITLE
ERROR TypeError: get_connect_fn(...) is not a function

### ISSUE THREAD

**Issue by brunoksi** [amqp/rhea#32]
Hi, I'm trying to use the rhea library with angular 2 + webpack. 
I get an exception when I run the following code:

**import  * as _ from 'rhea';
 _.on('connection_open', function (context) {
            context.connection.open_receiver('examples');
            context.connection.open_sender('examples');
        });
        _.on('message', function (context) {
            console.log(context.message.body);
            context.connection.close();
        });
        _.once('sendable', function (context) {
            context.sender.send({ body: payload });
        });
        _.connect({'host': 'localhost', 'port': 61616, 'user' : 'admin','password': 'admin', 'reconnect': true });**

**vendor.bundle.js:83229 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
main.bundle.js:397 o payload é undefined
ng:///ClientsMessageModule/ProducerComponent.ngfactory.js:220 ERROR TypeError: get_connect_fn(...) is not a function
    at Connection.webpackJsonp.../../../../rhea/lib/connection.js.Connection._connect (vendor.bundle.js:25781)
    at Connection.webpackJsonp.../../../../rhea/lib/connection.js.Connection.connect (vendor.bundle.js:25763)
    at Container.webpackJsonp.../../../../rhea/lib/container.js.Container.connect (vendor.bundle.js:26262)
    at AmqpService.webpackJsonp.../../../../../src/app/clients-message/services/amqp.service.ts.AmqpService.put (main.bundle.js:504)
    at ProducerService.webpackJsonp.../../../../../src/app/clients-message/producer/producer.service.ts.ProducerService.send (main.bundle.js:456)
    at ProducerComponent.webpackJsonp.../../../../../src/app/clients-message/producer/producer.component.ts.ProducerComponent.OnClick (main.bundle.js:398)
    at Object.eval [as handleEvent] (ng:///ClientsMessageModule/ProducerComponent.ngfactory.js:226)
    at handleEvent (vendor.bundle.js:92351)
    at callWithDebugContext (vendor.bundle.js:93810)
    at Object.debugHandleEvent [as handleEvent] (vendor.bundle.js:93398)
View_ProducerComponent_0 @ ng:///ClientsMessageModule/ProducerComponent.ngfactory.js:220
proxyClass @ vendor.bundle.js:67538
webpackJsonp.../../../core/@angular/core.es5.js.DebugContext_.logError @ vendor.bundle.js:93750
webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError @ vendor.bundle.js:81384
(anonymous) @ vendor.bundle.js:89578
(anonymous) @ vendor.bundle.js:104101
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.bundle.js:2838
onInvokeTask @ vendor.bundle.js:84228
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.bundle.js:2837
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ polyfills.bundle.js:2605
ZoneTask.invoke @ polyfills.bundle.js:2900
ng:///ClientsMessageModule/ProducerComponent.ngfactory.js:220 ERROR CONTEXT DebugContext_
View_ProducerComponent_0 @ ng:///ClientsMessageModule/ProducerComponent.ngfactory.js:220
proxyClass @ vendor.bundle.js:67538
webpackJsonp.../../../core/@angular/core.es5.js.DebugContext_.logError @ vendor.bundle.js:93750
webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError @ vendor.bundle.js:81389
(anonymous) @ vendor.bundle.js:89578
(anonymous) @ vendor.bundle.js:104101
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.bundle.js:2838
onInvokeTask @ vendor.bundle.js:84228
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.bundle.js:2837
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ polyfills.bundle.js:2605
ZoneTask.invoke @ polyfills.bundle.js:2900**

**Comment by alainpham** [comment]
Hi,
I ran into the same issue when trying to connect to the broker within an angular app. I believe it's not possible to use the straight forward AMQP connect method within a browser like you would do in a nodejs environment. I think you need to use the websocket layer to do so as shown in the examples.
I managed to get working demo here : 

https://github.com/alainpham/techlab-angular-amq7

Alain

**Comment by grs** [comment]
Yes, you need to use websockets from the browser.

**Comment by jfabdo** [comment]
Use this `websockets` example from the rhea github: https://github.com/amqp/rhea/blob/HEAD/examples/websockets/client.html

**Comment by jfabdo** [comment]
`rhea` has a`websockets` that works out of the box: https://github.com/amqp/rhea/blob/HEAD/examples/websockets/client.html

**Comment by jfabdo** [comment]
`rhea` has a`websockets` example that works out of the box: https://github.com/amqp/rhea/blob/HEAD/examples/websockets/client.html
