### ISSUE TITLE
How to implement an ActiveMQ Topic function？

### ISSUE THREAD

**Issue by 499689317** [amqp/rhea#322]
One of my requirements is that I want a Topic function of ActiveMQ. The current problem is that when I use multiple different Receiver instances to listen to the same queue messages, only one Receiver will receive the messages, and these different receivers will be initialized in different processes. What should I do if I want to implement this publish/subscribe requirement? I'm not sure if this can only be done in the same Container or Session

**Comment by 499689317** [comment]
I've looked at all the source code, but I still can't figure out how to set up this published-subscribe feature. I hope the author can give me some hints, thank you very much

**Comment by grs** [comment]
The distinction between topic and queue is a broker side concern. From the client, all that changes is the source/target address you use. In ActiveMQ I believe you can indicate a topic explicitly by prefixing with 'topic://'.

**Comment by 499689317** [comment]
@grs Thank you for your answer, which has solved my problem.

But I also have a question. If I want to control whether the message is processed successfully by myself, I look at the source code by listening to the `message` event and calling the `delivery.update` method, but I find that the `update` method does nothing internally,I'm not sure if I need to override this method to implement this requirement?
````
Incoming.prototype.update = function (delivery, settled, state) {
    if (delivery) {
         delivery.settled = settled;
         if (state ! == undefined) delivery.state = state;
         if (! delivery.remote_settled) {
            this.updated.push(delivery);
         }
         delivery.link.connection._register();
    }
};
function auto_accept(context) {
    context.delivery.update(undefined, message.accepted().described());
}
````
I want to use an ACK in my code to control whether a message is actually received successfully

**Comment by grs** [comment]
To manually acknowledge, you should set the `autoaccept` option for the receiver (or indeed connection or container) to false. The actual acknowledgement is then done by calling `context.delivery.accept()`

**Comment by 499689317** [comment]
@grs thank you very much for your answer. 
And are you the author of the package`amqp10`? I tested the `amqp10` package with `rhea` before, and I found that it could be used normally on node@v8.x, but it could not be used normally after upgrading to the version above node@v10.x, and finally I chose `rhea`,although the codes of these two packages have some similarities

**Comment by grs** [comment]
> are you the author of the packageamqp10?

No, I am not
