### ISSUE TITLE
Browserify rhea module is actually not working

### ISSUE THREAD

**Issue by aravmuki53** [amqp/rhea#325]
I have
rhea.js library version 1.0.24
browserify version 17.0.0,
node version is 12.16.3
npm version is 6.14.5.

When i do npm install on rhea zip folder , it installs everything and then when i try running the command of browserify script in rhea library's package.json :
**"browserify": "browserify -r .:rhea -o dist/rhea.js",**
it does not create a browserified version of rhea module. The created output rhea.js file still starts with require keyword. What i have observed is, if it has created a browserified version , it will start with a closure function. Am i missing anything or any dependency needs to be added to create the browserified version of rhea ?

**Comment by grs** [comment]
What is the first line of the browserified file? It is supposed to start with require, but it is defining it as a function. Have you tried using that file?

**Comment by aravmuki53** [comment]
require=(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){

},{}],2:[function(require,module,exports){



This is the first line of the browserified file. 


When i try using the browserified file in typescript file(for angular application like:

const rhea = require('./rhea.js');


the rhea does not have anything, it is an empty object, when i debugged.  The browserified .js file is properly placed it to the current folder onto the file i am writing this require keyword.

**Comment by grs** [comment]
That is a correctly browserified file.

The normal usage is to have a script tag that references the file and the use the module name 'rhea' in the require.

**Comment by aravmuki53** [comment]
Can we not use this browserified file in a typescript file using require keyword ?
const rhea = require('./rhea.js');

**Comment by grs** [comment]
I think you would usually import or require the actual rhea module then browserify your application which would pull in dependencies.

**Comment by aravmuki53** [comment]
I had previously browsified version of rhea.js starting like below:
(function (f) { if (typeof exports === "object" && typeof module !== "undefined") { module.exports = f() } else if (typeof define === "function" && define.amd) { define([], f) } else { var g; if (typeof window !== "undefined") { g = window } else if (typeof global !== "undefined") { g = global } else if (typeof self !== "undefined") { g = self } else { g = this } g.rhea = f() } })(function () {



But now when i try running browsify, it generates a file starting with require keyword like below:
require=(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){

Could we generate the previous browsified version file which has Immediately invoked function expression file ? using the browserify command

**Comment by grs** [comment]
My guess would be that the version of browserify may have changed. You could also try with the --standalone option perhaps.

**Comment by aravmuki53** [comment]
Yes, with standalone option, it created the version like IIFE file of rhea.js. Thank you much. Executed the command like below:
browserify -r .:rhea > dist/rhea.js -s rhea
