### ISSUE TITLE
Is AMQP transaction support planned?

### ISSUE THREAD

**Issue by richardpark-msft** [amqp/rhea#333]
Looking in the  rhea code it doesn't appear that some of the performatives needed for transactions (like 'declare') are currently implemented.

Is there any work in-process or planned around transaction support?

(Transactions as defined here: http://docs.oasis-open.org/amqp/core/v1.0/cos01/amqp-core-transactions-v1.0-cos01.html#toc)

**Comment by grs** [comment]
Nothing in-process and nothing planned as yet.

**Comment by richardpark-msft** [comment]
Thank you @grs, will close.
