### ISSUE TITLE
How can I change saslMechanisms to "PLAIN" and vhost to "default"

### ISSUE THREAD

**Issue by Jycjmf** [amqp/rhea#351]
Hi , I tried to connect to "a16083d328.iot-amqps.cn-north-4.myhuaweicloud.com" in C#.  According to the API doc in AMQP Server I used , I need to change sasl Mechanisms to "PLAIN" and vhost to "default". Just like this in java with Apache Qpid JMS library:
```
 String connectionUrl = "amqps://a16083d328.iot-amqps.cn-north-4.myhuaweicloud.com:5671?amqp.vhost=default
                                        &amqp.idleTimeout=8000
                                        &amqp.saslMechanisms=PLAIN";

  Hashtable<String, String> hashtable = new Hashtable<>();
        hashtable.put("connectionfactory.HwConnectionURL", connectionUrl);
        hashtable.put(Context.INITIAL_CONTEXT_FACTORY, "org.apache.qpid.jms.jndi.JmsInitialContextFactory");
        Context context = new InitialContext(hashtable);
        JmsConnectionFactory cf = (JmsConnectionFactory) context.lookup("HwConnectionURL");
```
The code above can work well in java.
![image](https://user-images.githubusercontent.com/30173232/117539505-92f5ad80-b03d-11eb-9548-ea792e45258a.png)

But in this library, I only saw the "factory.AMQP.HostName " rather than vhost. And the "factory.SASL.Profile" only have "External" and "Anonymous", when I try to do that like below:
```
 Address address = new Address("a16083d328.iot-amqps.cn-north-4.myhuaweicloud.com", 5671, user, password);
            var factory = new ConnectionFactory();
            factory.AMQP.HostName = "default";
            factory.AMQP.IdleTimeout = 80000;
            factory.SASL.Profile=SaslProfile.Anonymous;
            Console.WriteLine(SaslProfile.Anonymous.Mechanism);
            var connection = factory.CreateAsync(address).Result;
```
It throw "AmqpException: Sasl negotiation failed with code Auth". 
![image](https://user-images.githubusercontent.com/30173232/117539517-a0ab3300-b03d-11eb-9d50-7fb62f252c1a.png)

What should  I do to solve this problem? Thanks!

**Comment by grs** [comment]
If you specify a username and password in the connection options, PLAIN will be enabled automatically (see https://github.com/amqp/rhea/blob/master/examples/sasl/simple_sasl_client.js#L31).  There is no such thing as vhost in AMQP 1.0, but you can set the hostname option in the connection options. (not sure what you are referring to by 'this library').

**Comment by Jycjmf** [comment]
> If you specify a username and password in the connection options, PLAIN will be enabled automatically (see https://github.com/amqp/rhea/blob/master/examples/sasl/simple_sasl_client.js#L31). There is no such thing as vhost in AMQP 1.0, but you can set the hostname option in the connection options. (not sure what you are referring to by 'this library').

@grs 
Sorry bro , I have mistake this library for another😂.But what you replay have solved my problems . Thanks!
