### ISSUE TITLE
Sender Connection Closed forcibly but reconnect not stopped

### ISSUE THREAD

**Issue by Abhishek150995** [amqp/rhea#356]
I am trying to open a sender connection with reconnect functionality
container.connect({
                port: 5000,
                host: 127.0.0.1,
                username: admin,
                password: admin,
                reconnect: 5000
            }).open_sender('MY_QUEUE_NAME);

if receiver application is not started, I receive disconnected event wtih context.error.code = 'ECONNREFUSED'.
and keeps on retrying in very 5000msec. This works fine.

But later when I try to force close the connection using: context.connection.close();

The connection is not closed and I keep on receiving .on 'disconnected' event with context.error.code = 'ECONNREFUSED'

Please suggest how to close the connection

@grs Please suggest. Thanks in Advance.

**Comment by grs** [comment]
You can set `context.connection.options.reconnect = false` to stop the auto reconnect behaviour.
