### ISSUE TITLE
Can we enable add_credit(0) when draining?

### ISSUE THREAD

**Issue by richardpark-msft** [amqp/rhea#357]
(Note: I made an update below. Reading the AMQP spec more, I believe I was incorrect - we need to set receiver.credit = 0 to get the behavior I'm mentioning. Code snippet edited below)

I'm having an issue where I'd like to be able to initiate a drain on a link without adding in an additional credit.

My code looks like this:

```typescript
function receive_messages(number_of_messages: number) {
  receiver_link.add_credit(number_of_messages);
  // wait until timeout expires, then drain
  receiver.drain = true;
  receiver.add_credit(1);
}
```

The problem comes in with the 'add_credit(1)' line. After some logging and spelunking it looks like adding an additional credit can cause Service Bus to occasionally respond with an extra message since this credit gets sent along with the eventual `flow` frame from rhea. 

What I'd like to do is be able to call add_credit(0) and, so long as I'm draining, have that still enable a flow frame to be sent.

Currently the `.add_credit/.flow` code in rhea looks like this, which prevents that from working:

```typescript
   if (credit > 0) {
        this.credit += credit;
        this.issue_flow = true;
        this.connection._register();
    }
```

I was thinking we could change it to this (to signal that we want to receive no _further_ messages from the point when the drain frame is received):

```typescript
    // allow callers to specify 0 credits if they are attempting to drain.
    if (credit > 0) {
        this.credit += credit;
        this.issue_flow = true;
        this.connection._register();
    }

    if (credit === 0 & this.drain) {
        this.credit = 0;
        this.issue_flow = true;
        this.connection._register();
    }
```

From the AMQP spec, I believe this is the relevant section:

> drain
> The drain flag indicates how the sender SHOULD behave when insufficient messages are available to consume the current link-credit. If set, the sender will (after sending all available messages) advance the delivery-count as much as possible, consuming all link-credit, and send the flow state to the receiver. Only the receiver can independently modify this field. The sender's value is always the last known value indicated by the receiver.
> 
> **If the link-credit is less than or equal to zero, i.e., the delivery-count is the same as or greater than the delivery-limit, a sender MUST NOT send more messages.** If the link-credit is reduced by the receiver when transfers are in-flight, the receiver MAY either handle the excess messages normally or detach the link with a transfer-limit-exceeded error code.

Is this a sensible change to make? I can submit a PR if so but I'm not familiar with this aspect of rhea's internals and I wanted to check if this is even the correct direction. From my reading of the AMQP spec this should be allowed so this might just be an oversight.

**Comment by grs** [comment]
I don't object to that approach. Another option would be an explicit drain_credit() function on the receiver, e.g.:

```
Receiver.prototype.drain_credit = function() {
    this.issue_flow = true;
    this.connection._register();
};
```

**Comment by richardpark-msft** [comment]
> I don't object to that approach. Another option would be an explicit drain_credit() function on the receiver, e.g.:
> 
> ```
> Receiver.prototype.drain_credit = function() {
>     this.issue_flow = true;
>     this.connection._register();
> };
> ```

@grs , added in https://github.com/amqp/rhea/pull/358
