### ISSUE TITLE
Files in dist folder have not been updated for two years

### ISSUE THREAD

**Issue by woppa684** [amqp/rhea#360]
So, either update them when making a new release or drop them from the delivered package, since now I was having a really hard time in finding out what was wrong after updating to v2. I only found out now that the files in the dist folder are NOT on v2.

**Comment by grs** [comment]
Update now, will try and remember tp update before releases(!).

**Comment by woppa684** [comment]
Thanks, would it also be possbile to create a release with these files in?

**Comment by grs** [comment]
Updated dist now in 2.0.4
