### ISSUE TITLE
is this library amqp1.0 compliant?

### ISSUE THREAD

**Issue by amarzavery** [amqp/rhea#37]
Hello,

I was looking at the node-amqp10 library and this one. I wanted to know 
- if rhea is AMQP 1.0 compliant?
- how is this different from node-amqp10?
- Can this be used with Azure ServiceBus? Are there any examples?

**Comment by grs** [comment]
Yes, it is a 1.0 implementation. There are several general purpose examples. I have run these against different brokers/servers but not specifically against Azure ServiceBus.

**Comment by amarzavery** [comment]
Hi @grs,

We are super excited about this library and would like to talk to you. Is it possible to have a skype call with you and other team members? My email address is amzaveryATmicrosoftdotcom. It would be nice if you could send me and email and I can set up a quick syncup in the coming week as per your time convenience.

Thanks,
Amar
