### ISSUE TITLE
Should I close sender for different destinations?

### ISSUE THREAD

**Issue by akaNightmare** [amqp/rhea#372]
Hello,

I have tons of topics/virtual topics/queues and etc and I don't know the names(destinations) it's calculated on a fly.
Should I create a sender and after sending the message close it?
example
```js
const sender = connection.open_sender({ target: `topic://VirtualTopic.${someProperty}` });
sender.once('sendable', () => {
    sender.send({ body: 'Hello World!' });
    sender.close();
});
```

Thanks in advance.

**Comment by grs** [comment]
You can do that. There is also an 'anonymous' sender, where the link does not specify the target address but you specify a 'to' property on every message sent (see https://github.com/amqp/rhea/blob/main/examples/server.js#L26). That is exposed as a send() method on the connection (see https://github.com/amqp/rhea/blob/main/examples/server.js#L30).

**Comment by akaNightmare** [comment]
@grs Thank you.
