### ISSUE TITLE
Some common questions

### ISSUE THREAD

**Issue by akaNightmare** [amqp/rhea#374]
Hello,
I'm wondering about the following features in this lib:
1. failover(cluster re/connection + round-robin)
2. How to check that the message was sent to the broker successfully (with guarantee)
3. transactions - as I understand  - it's not implemented yet

Thanks in advance

**Comment by grs** [comment]
1. automatic reconnection is supported. To use different hosts you need to specify a connection_details function, e.g. https://github.com/amqp/rhea/blob/main/examples/reconnect/client.js#L43
2. a positive acknowledgement will result in an on_accepted() event (see https://github.com/amqp/rhea/blob/main/examples/simple_send.js#L35)
3. transactions are not supported
