### ISSUE TITLE
How to implement TCP keep-alive in the client applicaiton

### ISSUE THREAD

**Issue by happyoka** [amqp/rhea#386]
How to implement TCP keep-alive for my client application? I want to maintain the connection between the client and the application. What is different between is_open and is_remote_open? 

Any heartbeat mechanism ?

**Comment by grs** [comment]
AMQP has its own heartbeating. Each side can request that the other send heartbeats at a particular frequency using the `idle_time_out` option to the connection.

To set keepalive on the underlying socket you would need to provide a wrapper function for net.connect as the `connect` option to the connection.

**Comment by happyoka** [comment]
thank you for the explanation about the heartbeat. 

1) Do I need to set any value in the idle_time_out option in the connection to support TCP keep-alive? 
2) Do you have any example of set keepalive on the underlying socket?

**Comment by happyoka** [comment]
Thank you so much. If the TCP Keep-alive is enabled, empty message is sent to keep the TCP alive. Am I right

**Comment by grs** [comment]
TCP keepalive will cause the TCP layer to send a TCP packet if nothing is sent for a particular period. (AMQP heartbeats cause the AMQP layer to send an empty AMQP frame; AMQP sits above TCP)

**Comment by happyoka** [comment]
ok thank you :)

**Comment by happyoka** [comment]
Thank you @grs . I finally understand after seeing the packet flow using Wireshark. Just curious, how do we send empty AMQP frame to message broker using rhea library? Is it good practice to send empty AMQP frame to message broker to keep the TCP connection alive?

**Comment by grs** [comment]
That is under the control of the broker. You can set the `idle_time_out` option when calling `connect` andthat will tell the broker to send the client empty frames. If the broker wants empty frames from the client it will also set the `idle_time_out` and the client will then automatically send empty frames when needed.

**Comment by jmargieh** [comment]
Hi @grs ,

I'm interested to implement the keepalive, however I'm using rhea-promise.

this is how I create the connection:
```typescript
		const container = new Container({
			id: `${connectionToken}:${new Date().getTime()}`.toLowerCase(),
		});
		const connection: Connection = container.createConnection({
			...connectionOptions,
			id: connectionToken
		});
```
 Where should I pass the keepalive_connect function?

Thanks for the help!

**Comment by grs** [comment]
I *think* you can just use the rhea connection options, though a field 'connect' ?

**Comment by jmargieh** [comment]
The application is written in typescript and I am using rhea-promise:
https://github.com/amqp/rhea-promise/blob/master/lib/connection.ts#L107 does not have 'connect' property, hence I'm getting `.. is not assignable to parameter of type 'ConnectionOptions'.` since connect is not available.

**Comment by jmargieh** [comment]
@grs , had to bump the `rhea` dependency version from 2.0.8 to 3.0.1. not the connect property is available, thanks :)

**Comment by grs** [comment]
I think it may be ```connection_details.connect```

https://github.com/amqp/rhea/blob/main/typings/connection.d.ts#L55

https://github.com/amqp/rhea/blob/main/typings/connection.d.ts#L198

**Comment by jmargieh** [comment]
connection_details does not exist also on ConnectionOptions: https://github.com/amqp/rhea-promise/blob/master/lib/connection.ts#L107

**Comment by grs** [comment]
Did you get it working with 3.0.1? I'm not really familiar with typescript, or with the rhea-promise library I'm afraid. However the ConnectionOptions you reference seem to include RheaConnectionOptions which do, I believe, have the connection_details.

**Comment by jmargieh** [comment]
Should wait for rhea-promise to consume the latest rhea version.
As a workaround I am reconnecting whenever `disconnected` event is emited.

Currently I am trying to figure out when a disconnection event of an idle timeout is emited.
I want to handle disconnection event of idle timeout differently from other dissconnetion events.
According to - https://github.com/amqp/rhea/blob/main/lib/connection.js#L603, there is a specific error message for idle timeout exceeded, however somehow I'm not getting that message.

**Comment by grs** [comment]
The line you refer to is used to indicate to the peer that it did not send a heartbeat as expected, so you won't see that locally.

**Comment by jmargieh** [comment]
@grs , is there anyway to detect `idle_time_out` reached on the `disconnect` event?

**Comment by grs** [comment]
No

**Comment by happyoka** [comment]
Hi @grs, the following code can work in window. However, when i try to run in the ubuntu, i have the following error: 
{\"errno\":-104,\"code\":\"ECONNRESET\",\"syscall\":\"read\"}. Do you have any idea how to solve it?

````
    keepaliveConnection(...args) {
        // @ts-ignore
        const socket = net.connect(...args);
        socket.setKeepAlive(true);
        return socket;
    }
``

**Comment by happyoka** [comment]
Hi @grs, the following code is able to work for amqp(5672). However, it cannot work for amqp over tls/ssl (5671).

````
