### ISSUE TITLE
Get message body after sending confirms its accepted

### ISSUE THREAD

**Issue by Justgo13** [amqp/rhea#415]
I have a sender setup that sends message encoded using protobuf format.

I want to look at the message on_accepted handler to verify message was sent and update a database entry for this particular message.
When I print context I see a delivery object but that data field doesnt decode to the same message.

How can i do this?

**Comment by grs** [comment]
You would need to retain your own map of sent but not accepted, and retrieve the specific message from that using the delivery on accept. You could e.g. key on the delivery id or the delivery tag.

**Comment by Justgo13** [comment]
Ok will try that then
