### ISSUE TITLE
default properties for senders and receivers...

### ISSUE THREAD

**Issue by anthonyvercolano** [amqp/rhea#48]
Converting some code to utilize rhea.

With our other amqp transport we could specify properties on the amqp client constructor for default properties on the attach for sender and receiver links:

senderLink: {
         attach: {
           properties: {
             'client-version': '1.0'
           },
           maxMessageSize: 0,
         },

So that whenever we created a actual server link it would have at least the 'client-version' property.  When actually creating a sender link later on, we could optionally send further properties so that the link would have on the attach

properties: {
  'client-version': '1.0',
  'api-version': '2018',
  'channel-correlation': 'abc'
}

Is there a straight forward way of setting up the initial default property prior to actually creating the senderlink?

Thanks,
Tony

**Comment by grs** [comment]
At present there is no equivalent. I don't think it should be too difficult to add however, I'll take a look shortly.

**Comment by grs** [comment]
I've pushed a change that allows you to set 'sender_options' or 'receiver_options' on the session-, connection-, or container- options. Those values are then used as the defaults on subsequent open_sender() and open_receiver() calls. Only properties get merged, other fields in the options will be overwritten by any specific option in the open call.

E.g. 

```javascript
            var c = container.connect(listener.address());
            c.options.receiver_options = {properties:{'client-version': '1.0'}, max_message_size: 2048};
            /// then later...
            var r1 = c.open_receiver({source:'foo', properties:{'channel-correlation': 'abc'}});
            var r2 = c.open_receiver('bar');
            var r3 = c.open_receiver({source:'baz', max_message_size:1024});
```
r1 will have properties including both version and correlation, and a max-message-size of 2048
r2 will have just the client-version property and a max-message-size of 2048
r3 will have just the client-version property and a max-message-size of 1024

Fyi I will be away next week, but let me know if there you have any issues or comments on this and I'll get to them when I'm back. Thanks!
