### ISSUE TITLE
Why are log messages outbound different than inbound log messages...

### ISSUE THREAD

**Issue by anthonyvercolano** [amqp/rhea#57]
Here is a log message when sending a disposition to a peer:

rhea:frames [connection-1] PENDING: '{"channel":0,"type":0,"performative":[true,0,0,true,[]]}' +22ms
  rhea:raw [connection-1] SENT: <Buffer 00 00 00 1c 02 00 00 00 00 53 15 d0 00 00 00 0c 00 00 00 05 41 43 43 41 00 53 24 45> +110ms

The frame log really doesn't say that the performative is a dispostion.  You can look at the raw message to follow and see the 53 that indicates that the message is a disposition.  Additionally it doesn't give the values for role, settled, or state.

However, here is a disposition incoming from a peer:
 rhea:frames [connection-1] RECV: '{"size":23,"type":0,"channel":0,"performative":{"type":"disposition#15","role":true,"settled":true,"state":[]}}' +83ms

It does all those things.

Why the difference?

**Comment by grs** [comment]
I agree it is not ideal. The outgoing frames are in list form as they go out on the wire. I'll see what I can do to improve the logging.
