### ISSUE TITLE
Encoding a message_id as a uuid type.

### ISSUE THREAD

**Issue by anthonyvercolano** [amqp/rhea#60]
Utilizing amqp10 we can impose a type on our uuid properties message_id and correlation_id.

We  assign the property in the message object before sending it to amqp like so:

  if (typeof uuidString === 'string' && uuidString.match(uuidRegEx)) {
    uuid = (<any>amqp10).Type.uuid(uuidString);
  }

  When amqp10 serializes the data it will utilize the amqp uuid type.

Any thoughts on how this can be (or could be) accomplished with rhea?

**Comment by amarzavery** [comment]
- Based on [this test](https://github.com/amqp/rhea/blob/master/test/messages.js#L109), it looks like rhea will automatically serialize message_id as uuid type.
- For explicitly wrapping it as uuid you can take a look at [this test](https://github.com/amqp/rhea/blob/master/test/messages.js#L130).

**Comment by anthonyvercolano** [comment]
Ok, I changed the title.  Given an arbitrary property, what would be the recommended method for serializing out that property with the  0x98 encoding code followed by the 16 bytes of data.

**Comment by grs** [comment]
rhea.types.wrap_uuid(x)

**Comment by grs** [comment]
> Are message_id and correlation_id treated special?

Yes, in so far as they are properties that can take one of three defined types.

> If I set these properties to a simple number will it be serialized as a ulong (of appropriate size)?

Yes

> If I set these properties to a simple string (that doesn't look like a uuid), will it be set to one of the counted utf-8 string types?

Yes

> If I place a string in the either of these _id fields that look like a uuid is it going to be serialized as type uuid (with encoding code of 0x98)?

No, it will only be serialized as a uuid if it is a Buffer.

> If I place a buffer of length 16 bytes (which are returned by utils.uuid4()) in either of these _id fields will be be sent as a 0x98?

Yes

> If I place a buffer of length 16 bytes (which are returned by utils.uuid()) in either of these _id fields will be be sent as an array?

Assuming you mean uuid4(), then no, they will be sent as a uuid. (An array is not a valid type for message_id or correlation_id).

> If I force some arbitrary property (not correlation_id or message_id)

To send an application property, message- or delivery- annotation, or a field in a structured body as a UUID (i.e. 0x98 typecode) you need to explicitly tag it as such using types.wrap_uuid().

> When receiving a message:
> When receiving a message that contains a property that utilizes the encoding code of 0x98 the property into which it is placed will use:
> A 16 byte array?

Yes

> A string?

No, though you can get the string using util.uuid_to_string()

**Comment by anthonyvercolano** [comment]
Thank for all the information.  It simplified what I was trying to do.
