### ISSUE TITLE
Accepted event on a link object called how many times...

### ISSUE THREAD

**Issue by anthonyvercolano** [amqp/rhea#65]
I'm trying to track down what appears to be a double invocation of the event handler for 'accepted' event on the link object.

I have the code: self._linkObject.on('accepted', self._acceptedHandler.bind(this))

A bit further on in the code I have:

let sendDeliveryObject = this._linkObject.send(message);

It would appear as thought the event handler is invoked before the call to .send returns.  It is then invoked AGAIN when the actual message is accepted by the remote peer.

Is this expected behavior?

**Comment by anthonyvercolano** [comment]
Hmm, that one is a bit tricky.  It's part of my sdk converstion.  Let me see if I can gen something up standalone.

**Comment by amarzavery** [comment]
@anthonyvercolano - It could be a bug in rhea, However please make sure that you have not registered multiple event listeners. If you have added an event listener to an instance using the `.on()` method and forgot to remove it later then you would see the event handler being fired twice. I saw this behavior while developing the event hub sdk and realized that it was a mistake on my end. After fixing that I did not see multiple events being fired.

**Comment by anthonyvercolano** [comment]
I believe that there are only 4 event handlers on the link. error, accepted, rejected, released.  That's what seemed to be there in the debugger.

**Comment by anthonyvercolano** [comment]
Pilot error.  Sorry.
