### ISSUE TITLE
Getting unsupported protocol from my peer (server) when trying to connect using websockets.

### ISSUE THREAD

**Issue by anthonyvercolano** [amqp/rhea#69]
Essentially I have 

let uri = 'wss://totally-fake-hub.azure-devices.net:443/$iothub/websocket';
let webSocket = require('ws');
let ws = this._amqpContainer.websocket_connect(webSocket);
connectionParameters.connection_details = ws(uri);
connectionParameters.reconnect = false;
this._amqpSession.connect(connectionParameters);

Am I missing some vital piece?

**Comment by anthonyvercolano** [comment]
Further examination of my server logs indicates that the upgrade request isn't sending anything for the "subprotocol" that is part of the upgrade request.  The server folk tell me it should be AMQPWSB10.

**Comment by grs** [comment]
try:
```
connectionParameters.connection_details = ws(uri, ["binary", "AMQPWSB10", "amqp"]);
```

**Comment by anthonyvercolano** [comment]
Is it possible that it has to be sent in somehow to the ws with {protocols: ['AMQPWSB10']}?

**Comment by anthonyvercolano** [comment]
Ended up simply going ws(uri,'AMQPWSB10');

Thank you so much.
