### ISSUE TITLE
Question: events / containers, connections, sessions, senders, and receivers

### ISSUE THREAD

**Issue by anthonyvercolano** [amqp/rhea#74]
Hoping to get a complete picture of the events that the container, connection, session, sender, and receiver objects can emit.

Is it true to say that some of the events that can be emitted, where * is the above object names, *_open, *_close, *_error?  The listener for each of these events will passed a context parameter where the handler should look to the * property for further info?  So that if sender_error is invoked, one should look at context.sender.error for the error that caused the event to be emitted.

Will all of the above objects also be able to listen for a 'disconnected' event?  Will that listener still be sent the same context parameter and still be examined by the handler in the same way as the other events?

Is there ever an 'error' event sent to any of the above objects?

I've looked at the examples but, would there be some other thing I should be looking at in the source for other events?

Note that I am listening for sender: sendable, accepted, rejected, released.  For receiver I am listening for message.

**Comment by grs** [comment]
> Is it true to say that some of the events that can be emitted, where * is the above object names, *_open, *_close, *_error? The listener for each of these events will passed a context parameter where the handler should look to the * property for further info? So that if sender_error is invoked, one should look at context.sender.error for the error that caused the event to be emitted.

Yes, that is correct. These events all indicate the receipt of an amqp instruction/indication (or 'performative' as it is called in the spec) from the peer.

> Will all of the above objects also be able to listen for a 'disconnected' event? Will that listener still be sent the same context parameter and still be examined by the handler in the same way as the other events?

No, the disconnected event is only relevant for connections. It occurs when the underlying transport is lost.

> Is there ever an 'error' event sent to any of the above objects?

At present, the error is only issued at connection scope. (An event can always be handled at a wider scope that the subject object. E.g. a sender_close is is scoped to the sender and so can be handled on that sender, but if not handled there on the owning session, if not handled there the owning connection or finally if not handled on any of these, on the owning container.) 

Other events:

* settled for both sender and receiver scope (raised when a delivery is settled by the peer)
* receiver_flow and sender_flow (raised when a flow is received for receiver or sender)
* sender_draining (raised when a sender has been asked to drain credit)
* receiver_drained (raised when the receiver is informed that the peer has drained all credit)

**Comment by anthonyvercolano** [comment]
Would a disconnect event necessarily cause a *_error or *_close to be emitted?

**Comment by grs** [comment]
> Would a disconnect event necessarily cause a *_error or *_close to be emitted?

No, it would never cause a *_error or *_close as those are only emitted on receipt of a frame from the peer.
