### ISSUE TITLE
Queued events delivered when reconnecting?

### ISSUE THREAD

**Issue by anthonyvercolano** [amqp/rhea#75]
Perhaps there is an error in my code...

I decide to close a connection.  Due to some previous interactions with the peer the close performative received will contain an error.  So my client gets a connection_error.  Perhaps foolishly, I see the error and simply assume that all is done remove all listeners and return up to my calling clients.

My calling clients not that I have disconnected they want to persevere and ask me to connect again.
I connect.  I immediately get a connection_close.

1) Is this expected?
2) Could I have "drained" the event queue?
3) Should I code things so that if I get a *_error, I will always get a *_close?

**Comment by grs** [comment]
Yes, a *_error will always be accompanied by a *_close. The latter indicates the receipt of the closing frame from peer (close, end or detach) and the former indicates it was a frame with an error condition set.
