### ISSUE TITLE
connection.d.ts error

### ISSUE THREAD

**Issue by JB411** [amqp/rhea#77]
*** New to Angular and npm/node ***

{
	"resource": ".../rhea/typings/connection.d.ts",
	"owner": "typescript",
	"code": "2305",
	"severity": 8,
	"message": "Module '\"tls\"' has no exported member 'PeerCertificate'.",
	"source": "ts",
	"startLineNumber": 11,
	"startColumn": 10,
	"endLineNumber": 11,
	"endColumn": 25
}

I get this error when trying to setup Azure-Event-hubs.  

Are there versions of libraries that need to line up?  

Here is my package.json
{
  "name": "dotapp",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "'@'angular/animations": "^5.2.0",  (adding single quotes around '@' so they show)
    "'@'angular/common": "^5.2.0",
    "'@'angular/compiler": "^5.2.0",
    "'@'angular/core": "^5.2.0",
    "'@'angular/forms": "^5.2.0",
    "'@'angular/http": "^5.2.0",
    "'@'angular/platform-browser": "^5.2.0",
    "'@'angular/platform-browser-dynamic": "^5.2.0",
    "'@'angular/router": "^5.2.0",
    "'@'types/async-lock": "^1.1.0",
    "'@'types/azure": "^0.9.19",
    "'@'types/chai": "^4.1.4",
    "'@'types/chai-as-promised": "^7.1.0",
    "'@'types/debug": "0.0.30",
    "'@'types/dotenv": "^4.0.3",
    "'@'types/mocha": "^5.2.2",
    "'@'types/uuid": "^3.4.3",
    "angular-bootstrap-md": "^6.1.1",
    "async-lock": "^1.1.3",
    "azure-event-hubs": "^0.2.2",
    "browserify": "^16.2.2",
    "chai": "^4.1.2",
    "chai-as-promised": "^7.1.1",
    "chart.js": "^2.7.2",
    "core-js": "^2.4.1",
    "debug": "^3.1.0",
    "dotenv": "^6.0.0",
    "eslint": "^4.19.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "is-buffer": "^2.0.3",
    "istanbul": "^0.4.5",
    "minimist": "^1.2.0",
    "mocha": "^5.2.0",
    "ms-rest": "^2.3.4",
    "ms-rest-azure": "^2.5.7",
    "require-self": "^0.2.1",
    "rhea": "^0.2.13",
    "rxjs": "^5.5.6",
    "uglify-js": "^3.4.0",
    "uuid": "^3.2.1",
    "ws": "^5.2.0",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "'@'angular/cli": "~1.7.4",
    "'@'angular/compiler-cli": "^5.2.0",
    "'@'angular/language-service": "^5.2.0",
    "'@'types/jasmine": "~2.8.3",
    "'@'types/jasminewd2": "~2.0.2",
    "'@'types/node": "^10.3.3",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.3.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}

Also new to asking for help on here, so if you need more info I'll provide it.  Thanks in advance for any help!

**Comment by JB411** [comment]
For whatever reason this issue isn't an issue anymore.  I traced back down the rabbit hole and found PeerCertificate staring me in the face in the tls module.  When it saw me, the error went away.  Angular is trying to F with me.  I don't know if I like this.

**Comment by swaathee** [comment]
Facing the same error.
