### ISSUE TITLE
Failover support?

### ISSUE THREAD

**Issue by ps2goat** [amqp/rhea#78]
Note: The maintainer of `node-amqp10` forwarded me to this library, so I'm asking the same question as was on [there](https://github.com/noodlefrenzy/node-amqp10/issues/370).

For ActiveMQ, in the Java world, there is the idea of a failover connection. Is there support for this in this library? With AmazonMQ, we have two possible instances to connect to, and either one can be up at any given time (but only one will be available).

**Comment by grs** [comment]
Yes. The library has built in reconnect logic which will also re-establish any sender/receiver links. If you want to alternate between different connection options you can use the connection_details option on connect which should be a function that returns the options to use.

There is an example (https://github.com/amqp/rhea/blob/master/examples/reconnect/client.js#L43) using this to iterate over a set of defined ports. That approach can be sued to have different hosts or any other connection details that needs to vary.

**Comment by ps2goat** [comment]
It looks like that approach is working for me, thanks.

I think there is an error in the example, though.  Both the port and host are using `attempt++`, which means if I have two connections with two different ports, each would be using the wrong port (or the wrong host, depending on your view).

```
connection_details: function() {
        return {
            port: args.ports.length ? args.ports[attempt++ % args.ports.length] : args.ports,
           // code below should just use 'attempt' instead of 'attempt++'
            host: args.hosts.length ? args.hosts[attempt++ % args.hosts.length] : args.hosts
        };
    }
```

Also, for other people using this, I had to dig through the code to find that the use of the `connection_details` property on the connection options _also_ requires returning the `transport` property if you want a secure connection.  I was setting it on the connection options and still getting errors.  A good broker should be secure!  Here's my altered function:

```
var attempt = 0;
var connectOptions = {
username = 'yourusername',
password = 'your unencoded password',
// i'm not sure if this is used elsewhere in the code base, so I left it at the top-level, too.
transport: 'ssl',
connection_details: function() {
        attempt++;
        return {
            port: args.ports.length ? args.ports[attempt % args.ports.length] : args.ports,
            host: args.hosts.length ? args.hosts[attempt % args.hosts.length] : args.hosts,
            transport: 'ssl'
        };
    }
}

```

**Comment by grs** [comment]
Thanks! I have pushed a fix for the example and will try and get some time to improve the docs and perhaps also see if the behaviour can be improved a little.

**Comment by grs** [comment]
@amarzavery that is not quite the correct return type (at present), it should be an object with host, port and options fields, and the options can be all the options in ConnectionOptions except host and port.

**Comment by amarzavery** [comment]
I see. What about the transport property that @ps2goat mentioned in the [above comment](https://github.com/amqp/rhea/issues/78#issuecomment-398445542) ?

**Comment by grs** [comment]
That is one of the options in ConnectionOptions.

**Comment by ps2goat** [comment]
`transport` was expected to be specified in the return object from `connection_details`.  If that's the "behavior modification" you are referring to (looking for `transport` on the connection options), then that sounds good.  I would expect the transport to be the same for all hosts.

**Comment by amarzavery** [comment]
@grs - Can you release a new version which will have changes from the merged PR?

**Comment by akej74** [comment]
I hope it's OK with a follow up question on this after 6 years :-) 

In "connection.js", we have the call to _connect with the return value from "connection_details":

```
Connection.prototype.connect = function () {
    this.is_server = false;
    if (this.abort_idle) {
        clearTimeout(this.abort_idle);
        this.abort_idle = undefined;
    }
    this._reset_remote_state();
    this._connect(this.options.connection_details(this.conn_established_counter));
    this.open();
    return this;
};
```
Here the `conn_established_counter` is provided as an argument, and it's increased here:

```
Connection.prototype.connected = function () {
    this.socket_ready = true;
    this.conn_established_counter++;
    log.io('[%s] connected %s', this.options.id, get_socket_id(this.socket));
    this.output();
};
```
So, would it work to just rely on this argument instead of creating an "attempt" variable as discussed above?
