### ISSUE TITLE
Is batching supported?

### ISSUE THREAD

**Issue by ps2goat** [amqp/rhea#81]
Is there a way to configure batching?  From a user standpoint, I would expect the `send` method on the `Sender` to allow me to pass an array of `Message`s.  I haven't looked at it from a `Receiver` point of view, yet.

I'm creating a batch of messages and applying a group id and sequence to them, and I was looking to send them all to the server at once for a potential performance boost.

**Comment by amarzavery** [comment]
rhea supports batching. I have implemented this for Azure Event Hubs where customers can send a batch of messages to the Event Hub. You can find it over [here](https://github.com/Azure/azure-event-hubs-node/blob/master/client/lib/eventHubSender.ts#L96-L125).

Receiving a batch of messages, is as simple as manipulating the credit_window. While creating the receiver set the credi_window to 0. This indicates rhea that you will be managing credits. Now, let's say you want 10 messages, then add_credit(10) and you will receive that many messages. I have implemented that functionality for Azure Event Hubs over [here](https://github.com/Azure/azure-event-hubs-node/blob/master/client/lib/batchingReceiver.ts#L120-L128). You can specify the number of messages you want to receive and the max wait timeout. You will receive an array of messages based on whichever happens first.

**Comment by ps2goat** [comment]
Thanks, @amarzavery, I'll try that. I was hoping for something built in without me having to manage credits directly.

**Comment by amarzavery** [comment]
You don't need to manage credits for sending batch messages. 
For receiving one more approach could be to set the credit-window to 1 and then call the receive in a loop for the number of messages you want.

**Comment by ps2goat** [comment]
@amarzavery - after reviewing the code you pointed out for receiving and testing rhea, it appears that the batching functionality you linked to is not durable.  From what I was testing in rhea, once you exit the event listener the ACK is sent back to the broker.  So if I wanted to receive a batch of 10 messages with that code (let's ignore the timer), I would be given 10 messages, already acknowledged.  If the process dies, I lose those 10 messages, correct?

I was hoping for a way to manually acknowledge that the message was processed.  Is this possible with rhea, even when processing a single message? This is likely a different issue, but relevant to the thread, I think.

**Comment by grs** [comment]
Yes, to manually accept you can turn of auto-accept on the receiver
