### ISSUE TITLE
session close frame with an error only seems to invoke a close.  No session_error

### ISSUE THREAD

**Issue by anthonyvercolano** [amqp/rhea#85]
I got the following trace in my code:

rhea:raw [connection-1] RECV: '0000004502000000005317c0380100531dc03203a313616d71703a696e7465726e616c2d6572726f72a119207365766572732074686520414d51502073657373696f6e2040' +8ms
  rhea:frames [connection-1] RECV: '{"size":69,"type":0,"channel":0,"performative":{"type":"end#17","error":{"type":"error#1d","condition":"amqp:internal-error","description":" severs the AMQP session "}}}' +8ms
  rhea:events Session got event: session_close +9ms

I would have expected to see a session_error event.  Am I mistaken?

**Comment by grs** [comment]
No, you are right, that is a bug. I'll get a fix in on Monday.
