### ISSUE TITLE
Odd log while testing disconnection

### ISSUE THREAD

**Issue by anthonyvercolano** [amqp/rhea#88]
I received the following frames while testing something.  I've adjusted the code in transport.js so that I can see entire frames.

 rhea:io [connection-8] got frame of size 15 +25ms
  rhea:raw [connection-8] RECV: '0000004b02000000005316c03e0352' +25ms
  rhea:frames [connection-8] RECV: '{"size":15,"type":0,"channel":0,"performative":{"type":"end#17"}}' +25ms

Note the raw frame.  It has a 16 following the 0053.  This I would have presumed is a detach frame.  However, the next line indicates that it thinks it is a session end frame.  Indeed, I do get a session_error event following it immediately.

**Comment by grs** [comment]
Can you create a reproducer?

**Comment by anthonyvercolano** [comment]
I'll see what I can do.  This is happening deep in some e2e disconnection tests between an IoT Hub and a client.  Pulling something out could be a bit difficult.  Wondered whether this would be a simple "doh!" type of bug.

**Comment by grs** [comment]
I've had a look and don't spot anything obvious. It certainly looks very odd. The raw detach doesn't look complete either, unless I am misreading the way it is printed. Is there any more log leading up to this?

**Comment by anthonyvercolano** [comment]
Yeah, it did seem short.  This is my change in the while loop of the transport.prototype.read function in transport.js

           var frame = frames.read_frame(buffer.slice(offset, offset + frame_size));
            log.raw('[%s] RECV: %o', this.identifier, buffer.toString('hex', 0, frame_size));
            log.frames('[%s] RECV: %o', this.identifier, JSON.stringify(frame));
   
Perhaps could be better.

**Comment by grs** [comment]
To be sure that the raw bytes match the decoded frame, I think that should be: 

```
    log.raw('[%s] RECV: %o', this.identifier, buffer.toString('hex', offset, offset + frame_size));
```

**Comment by anthonyvercolano** [comment]
Thanks.  I believe that might have been my problem and am using your change.
