### ISSUE TITLE
How to create/attach a link.

### ISSUE THREAD

**Issue by anthonyvercolano** [amqp/rhea#89]
What I currently do when I am creating a Sender or Receiver link is:
I have a Session object.
I have some options.

I call sessionObj.open_sender(option).  

I have some listeners on the session object to deal with the actual session_open emit and I also have other event listeners on the session object for the various other sender events that I might see later.  Whenever I create senders this way I create each sender with a unique name.  I can thus distinguish in my event handlers if this is an event that I care about.

What I would prefer:

I would like to create a Sender object.  Do this in a way that can't fail and doesn't cause network activity.  The only things I have to do this would be the session object and a set of options.
After the create happens I would like to add the event listeners that I care about onto this Sender object and then make a call that actually will issue the attach.  If there is an error it will invoke the event listener on the Sender object.

Sorry this is a very basic question.
Of course the same question holds true for Receiver objects.

**Comment by grs** [comment]
The open_sender() call won't fail and there will be no network output when it returns (that will only happen on the next tick). It is therefore safe to set listeners on the returned sender; no event will be raised before the listeners are set and control is returned to the event loop.

If this is still a concern, we could perhaps look at an addition to the api that would return a Sender/Receiver that you would then explicitly need to open().

**Comment by anthonyvercolano** [comment]
I'll admit to feeling a bit queasy on the thought of the nextTick.  Although I may change to simply accept that.  I've gone through various gyrations to keep myself defensive here.

The session code seems to have an interface more akin to what you suggest.  Currently I can do

sessionObject = connectionObject.create_sender();
sessionObject.open();

But the session event handlers actually live on the connection object.

We repeat this on connection object.  The handlers for the connection events live on the container object.

This works OK for the connections and sessions however, links like I said, I need to have the handlers check to see if the event is for the link object I care about (via doing a name check).

**Comment by anthonyvercolano** [comment]
So to sum up:

If I do:
connectionObj = containerObj.connect();
I have until the next tick before any network traffic will be generated.  So I can put listeners onto the connectionObj safely.

If I do:
senderObj = sessionObj.open_sender();
I have until the next tick before any network traffic will be generated.  So I can put listeners onto the senderObj safely.

Correct?

**Comment by grs** [comment]
Correct.
